Revert "media: Migrate DataSource::ReadCB to once callback."
This reverts commit a9df7cc85a6dcb45a63fd26b519af31e0a016081.

Reason for revert: Seems to be causing compile failures on multiple builders:
[2431/2474] CXX obj/chromeos/services/assistant/audio_decoder/lib/ipc_data_source.o
FAILED: obj/chromeos/services/assistant/audio_decoder/lib/ipc_data_source.o
../../build/cros_cache/chrome-sdk/symlinks/eve+12933.0.0+target_toolchain/bin/x86_64-cros-linux-gnu-...(too long)
In file included from ../../chromeos/services/assistant/audio_decoder/ipc_data_source.cc:5:
../../chromeos/services/assistant/audio_decoder/ipc_data_source.h:37:37: error: non-virtual member function marked 'override' hides virtual member function
const ReadCB& callback) override;
^

Original change's description:
> media: Migrate DataSource::ReadCB to once callback.
> 
> This callback is used to signal completion of the read operation,
> therefore, it's a once callback:
> * https://cs.chromium.org/chromium/src/media/base/data_source.h?rcl=6e8610f8f31aa3bb8266660380a66c6c25b2e64a&l=27
> 
> This is part of the base::Callback migration.
> 
> Context: https://cs.chromium.org/chromium/src/docs/callback.md?rcl=9fcc3764aea8f97e9f6de4a9ee61d554e67edcda&l=40
> 
> Bug: 714018
> Change-Id: Ie43febda1247be065f9f22cc4aec0d8412873491
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2056729
> Reviewed-by: Marc Treib <treib@chromium.org>
> Reviewed-by: Xiaohan Wang <xhwang@chromium.org>
> Reviewed-by: danakj <danakj@chromium.org>
> Commit-Queue: Jose Lopes <jabolopes@google.com>
> Cr-Commit-Position: refs/heads/master@{#745018}

TBR=danakj@chromium.org,xhwang@chromium.org,treib@chromium.org,jabolopes@google.com

Change-Id: I29a9ef7f049320a36dcd52212b7f5ac80e6fc02b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 714018,1056660
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2078593
Reviewed-by: Katie Dektar <katie@chromium.org>
Commit-Queue: Katie Dektar <katie@chromium.org>
Cr-Commit-Position: refs/heads/master@{#745053}