ScrollStateCallback: fix clash between enum class NativeScrollBehavior and getter
Rename NativeScrollBehavior getter to GetNativeScrollBehavior to avoid GCC
compilation error:

../../third_party/blink/renderer/core/page/scrolling/scroll_state_callback.h:31:3: error: declaration of ‘blink::NativeScrollBehavior blink::ScrollStateCallback::NativeScrollBehavior() const’ [-fpermissive]
   }
   ^
../../third_party/blink/renderer/core/page/scrolling/scroll_state_callback.h:15:12: error: changes meaning of ‘NativeScrollBehavior’ from ‘enum class blink::NativeScrollBehavior’ [-fpermissive]

Bug: 819294
Change-Id: Idb0fa5649c78171dce179a075222847053268324
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1900998
Reviewed-by: David Bokan <bokan@chromium.org>
Commit-Queue: José Dapena Paz <jose.dapena@lge.com>
Cr-Commit-Position: refs/heads/master@{#713116}