Fix warnings [unused-const-variable]
../../chromecast/media/cma/backend/volume_control.cc:50:17: error:
unused variable 'kMinDbFS' [-Werror,-Wunused-const-variable]
constexpr float kMinDbFS = -120.0f;
                ^
		1 error generated.

Change-Id: I787673a625feb4d23c304404f5b62e8f663b2d6a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2131247
Reviewed-by: Daniel Nicoara <dnicoara@chromium.org>
Commit-Queue: Michael Spang <spang@chromium.org>
Cr-Commit-Position: refs/heads/master@{#755158}