DarkModeFilter: Do not rely on C++20 features in DCHECK_NE call
Follow-up to commit 72bb0f1 ("Refactor DarkModeFilter and DarkModeColorClassifier.
"), which has a call that looks like

    DCHECK_NE(foo, nullptr);

where |foo| is a std::unique_ptr fails with libstdc++ because there is no
operator<< overload for std::unique_ptr until C++20 (libc++ just happens to
have it):

    ../../third_party/blink/renderer/platform/graphics/dark_mode_filter.cc:158:3: error: no matching function for call to 'MakeCheckOpValueString'
      DCHECK_NE(text_classifier_, nullptr);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../base/logging.h:851:31: note: expanded from macro 'DCHECK_NE'
    #define DCHECK_NE(val1, val2) DCHECK_OP(NE, !=, val1, val2)
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../base/logging.h:822:29: note: expanded from macro 'DCHECK_OP'
      EAT_STREAM_PARAMETERS << (::logging::MakeCheckOpValueString(      \
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../base/logging.h:635:18: note: candidate function not viable: no known conversion from 'std::unique_ptr<DarkModeColorClassifier>' to 'std::nullptr_t' (aka 'nullptr_t') for 2nd argument
    BASE_EXPORT void MakeCheckOpValueString(std::ostream* os, std::nullptr_t p);

Bug: 957519, 980914
Change-Id: Ieae7bb93921523894551f01a114e26a1f010585e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1683297
Commit-Queue: Stephen Chenney <schenney@chromium.org>
Reviewed-by: Stephen Chenney <schenney@chromium.org>
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#674828}