Revert "Add trailing whitespace and punctuation to UIA Move(TextUnit_Word)"
This reverts commit 6720f8ec468855461924e458ff0baebf9f8eec35.

Reason for revert: suspect causing content_browsertests failure on Windows bots:
E.g.
https://ci.chromium.org/p/chromium/builders/ci/Win10%20Tests%20x64/39015
deterministic failures
AXPlatformNodeTextRangeProviderWinBrowserTest.OutOfProcessIFrameTraversal
AXPlatformNodeTextRangeProviderWinBrowserTest.MoveEndpointByUnitFormat
AXPlatformNodeTextRangeProviderWinBrowserTest.MoveEndpointByUnitParagraph
AXPlatformNodeTextRangeProviderWinBrowserTest.EntireMarkupSuccessiveMoveByWord
AXPlatformNodeTextRangeProviderWinBrowserTest.IFrameTraversal
AXPlatformNodeTextRangeProviderWinBrowserTest.MoveEndpointByUnitFormatAllFormats
AXPlatformNodeTextRangeProviderWinBrowserTest.MoveEndpointByUnitParagraphCollapseTrailingLineBreakingObjects
AXPlatformNodeTextRangeProviderWinBrowserTest.ExpandToEnclosingFormat
AXPlatformNodeTextRangeProviderWinBrowserTest.GetBoundingRectangles

https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8906448482404732176/+/steps/content_browsertests_on_Windows-10-15063/0/logs/Deterministic_failure:_AXPlatformNodeTextRangeProviderWinBrowserTest.EntireMarkupSuccessiveMoveByWord__status_FAILURE_/0
[ RUN      ] AXPlatformNodeTextRangeProviderWinBrowserTest.EntireMarkupSuccessiveMoveByWord
...
../../content/browser/accessibility/ax_platform_node_textrangeprovider_win_browsertest.cc(360): error: Expected: (nullptr) != (text_range), actual: (nullptr) vs 8-byte object <00-00 00-00 00-00 00-00>

Original change's description:
> Add trailing whitespace and punctuation to UIA Move(TextUnit_Word)
> 
> 1. Changing the behavior of `ITextRangeProvider` methods `Move` and
>    `ExpandToEnclosingUnit` with `TextUnit_Word`.
> 
>    Previously we relied on both, word start and end offsets, computed
>    from Blink, but such approach didn't matched every AT's expectations.
> 
>    Updated logic makes use of start offsets only, this forces movement
>    by word to include whitespace and punctuation characters before the
>    next word start; the only special case being the last word, whose end
>    offset will be located after the last character on the document.
> 
> 2. Removing `AXPosition`'s methods `AsLeafTextPositionBeforeCharacter`
>    and `AsLeafTextPositionAfterCharacter` in favor of refactoring
>    `AsPositionBeforeCharacter` and `AsPositionAfterCharacter`.
> 
>    This is a follow-up optimization since the former methods called
>    their `AsLeafTextPosition` equivalents, but reverted the result if
>    the position was not adjusted to another anchor.
> 
> 3. Adding a new browser test to cover some AT's expectations.
> 
>    Rebaselining `AXPlatformNodeTextRangeProviderWin` unit and browser
>    tests to account for the new word movement behavior.
> 
> Bug: 928948
> Change-Id: Iab689fde2a2ea973e86f7cdb10c1c22cf1af1704
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1718064
> Commit-Queue: Ethan Jimenez <ethavar@microsoft.com>
> Reviewed-by: Kurt Catti-Schmidt <kschmi@microsoft.com>
> Reviewed-by: Nektarios Paisios <nektar@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#682564}

TBR=nektar@chromium.org,kschmi@microsoft.com,ethavar@microsoft.com

Change-Id: I855ecf6dbb5769c591d35bd6134164e5aeec37b3
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 928948
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1728130
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#682597}