IWYU: missing include for std::string in csp_source_list.h
Build error in GCC:
../../services/network/public/cpp/content_security_policy/csp_source_list.h:19:6: error: ‘string’ in namespace ‘std’ does not name a type

Bug: 819294
Change-Id: I9c8665050cae038530a79323b65932a124adf2a1
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2067074
Commit-Queue: Lucas Gadani <lfg@chromium.org>
Reviewed-by: Lucas Gadani <lfg@chromium.org>
Cr-Commit-Position: refs/heads/master@{#743946}