make_origin_trials: Convert use of itervalues()
itervalues() has been removed in Python 3.
Use values() which is functionally same on both Python 2 and 3 in this case.

Traceback (most recent call last):
  File "../../third_party/blink/renderer/build/scripts/make_origin_trials.py", line 128, in <module>
    json5_generator.Maker(OriginTrialsWriter).main()
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\json5_generator.py", line 337, in main
    writer = self._writer_class(args.files, args.output_dir)
  File "../../third_party/blink/renderer/build/scripts/make_origin_trials.py", line 52, in __init__
    for features in self._trial_to_features_map.itervalues())
AttributeError: 'dict' object has no attribute 'itervalues'

Bug: 941669
Change-Id: I474ae78b34dae62089dbcbd7f77d3358bf854733
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2125729
Auto-Submit: Raul Tambre <raul@tambre.ee>
Commit-Queue: Yuki Shiino <yukishiino@chromium.org>
Reviewed-by: Yuki Shiino <yukishiino@chromium.org>
Cr-Commit-Position: refs/heads/master@{#754406}