Revert "Work toward synchronizing feed store and model"
This reverts commit 1e688ea3c72d9d4c33ef50ad6ae52bd58eaed6f0.

Reason for revert: This CL breaks Clank build.
Failed builder: https://ci.chromium.org/p/chrome/builders/ci/arm64-builder-rel/21232

Compiler message:
../../components/feed/core/v2/feed_stream_unittest.cc:251:7: error: predefined identifier is only valid inside function [-Werror,-Wpredefined-identifier-outside-function]
      FROM_HERE, base::TimeDelta::FromSeconds(1)};
      ^
../../base/location.h:123:52: note: expanded from macro 'FROM_HERE'
#define FROM_HERE ::base::Location::CreateFromHere(__func__, __FILE__, __LINE__)
                                                   ^


Original change's description:
> Work toward synchronizing feed store and model
> 
> - Added LoadStreamFromStoreTask to read model data from the store.
> - Update LoadStoreTask to try loading from the store first, via the new
>   task.
> - Save operations executed to persistent storage.
> - Added some conversions to textproto for tests.
> 
> My primary goal when making this change was to save operations to
> persistent storage as they are executed. Pulling this thread led to
> several changes.
> 
> We were saving a bit too much data in the single 'stream_data' record,
> which meant we would have to re-serialize the whole model to save a
> single piece of information. I went ahead and split 'stream structures'
> out into another record. All stream structures for the stream now need
> to be read in at load time, and they need to be sequenced appropriately.
> 
> In making that change, I wanted to verify we could actually load the
> data back in. So I implemented loading a stream from storage as well.
> 
> Bug: 1044139
> Change-Id: I98767281b4a5d1ae401dba5db5bff966f3473452
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2123249
> Commit-Queue: Dan H <harringtond@chromium.org>
> Reviewed-by: Ian Wells <iwells@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#754782}

TBR=iwells@chromium.org,harringtond@chromium.org

Change-Id: I7a1955a0a4dbb76cf6d17497be63b8256218ca31
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1044139
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2129234
Reviewed-by: Pavel Yatsuk <pavely@chromium.org>
Commit-Queue: Pavel Yatsuk <pavely@chromium.org>
Cr-Commit-Position: refs/heads/master@{#754802}