Reland "Upstreaming ContentCapture"
This reverts commit 5347b384a8c8be437facafaf6cb0730f3ce99f8c.

Reason for revert: The downstream has rolled to my change, this
patch should be good to go.

Original change's description:
> Revert "Upstreaming ContentCapture"
> 
> This reverts commit edc475edfa7c9abcfcc0b84e782dfafaffe330b4.
> 
> Reason for revert: Causes compilation failure:
> https://logs.chromium.org/logs/chrome/buildbucket/cr-buildbucket.appspot.com/8895755054118235408/+/steps/compile/0/stdout
> 
> ../../clank/java/src/org/chromium/chrome/browser/compositor/CompositorViewHolderForQ.java:26: error: method does not override or implement a method from a supertype
>     @Override
>     ^
> 
> 
> 
> Original change's description:
> > Upstreaming ContentCapture
> > 
> > Related downstream change:
> > https://chrome-internal-review.googlesource.com/c/clank/internal/apps/+/2172237
> > 
> > Binary-Size: all added code was from downstream, the size increase is expected.
> > Bug: 951275
> > Change-Id: Ibf56135e2a7d2f437f167dc0cdb7761bce447e86
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1922603
> > Reviewed-by: Changwan Ryu <changwan@chromium.org>
> > Reviewed-by: Richard Coles <torne@chromium.org>
> > Reviewed-by: David Trainor <dtrainor@chromium.org>
> > Commit-Queue: Tao Bai <michaelbai@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#718894}
> 
> TBR=michaelbai@chromium.org,dtrainor@chromium.org,torne@chromium.org,changwan@chromium.org
> 
> Change-Id: Id904c28aa48d561ccea36942da1f507982a698dd
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 951275
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1935578
> Reviewed-by: Yoshifumi Inoue <yosin@chromium.org>
> Commit-Queue: Yoshifumi Inoue <yosin@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#719031}

TBR=michaelbai@chromium.org,yosin@chromium.org,dtrainor@chromium.org,torne@chromium.org,changwan@chromium.org

Change-Id: I1aeb6ccb43989d58aa872860d2048b1eff2815ee
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 951275
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1936969
Reviewed-by: Tao Bai <michaelbai@chromium.org>
Commit-Queue: Tao Bai <michaelbai@chromium.org>
Cr-Commit-Position: refs/heads/master@{#719161}