Revert "[remoting][IT2ME] Register support host over remoting API"
This reverts commit 7432ef1a0cef826dda3c0d12b03ce70686db1dba.

Reason for revert: suspect compile failure on mac-archive-dbg
https://ci.chromium.org/p/chromium/builders/ci/mac-archive-dbg/12

https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8913230298494458928/+/steps/compile/0/stdout

gen/remoting/proto/remoting/v1/remote_support_host_messages.pb.h:32:10: fatal error: 'host_info.pb.h' file not found
#include "host_info.pb.h"
         ^~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> [remoting][IT2ME] Register support host over remoting API
> 
> This CL adds a RemotingRegisterSupportHostRequest that registers an
> IT2ME host using the new remoting API. This will be used for the
> ChromeOS enterprise use case but the website will still use the old
> XMPP-based registration request until it is updated to support that.
> 
> Bug: 962765
> Change-Id: Ifcf2eb6eaba76db6386ae27f86f20e06088383f0
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1611023
> Commit-Queue: Yuwei Huang <yuweih@chromium.org>
> Reviewed-by: Joe Downing <joedow@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#660738}

TBR=joedow@chromium.org,yuweih@chromium.org

Change-Id: I1bb37164ca6329bc0b9bb67568e26c038bf6a4ba
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 962765
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1617048
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#660760}