Reland "Better registry cleanup in InstallServiceWorkItemTest."
This reverts commit b99538b3078f11e6d63dec9d2eb7a45854ab9045.

Reason for revert: The original CL 2092939 was not the cause of the flaky failures, so reverting the revert.

Original change's description:
> Revert "Better registry cleanup in InstallServiceWorkItemTest."
> 
> This reverts commit b256ed1fcec351ccab9b2b20169e37b4d8eeb0b3.
> 
> Reason for revert: I'm hoping reverting this and your other patch will fix the flake. Bug is here: https://bugs.chromium.org/p/chromium/issues/detail?id=1059314
> 
> Original change's description:
> > Better registry cleanup in InstallServiceWorkItemTest.
> > 
> > mini_installer_tests ChromeUserLevel and ChromeUserLevelUpdate are
> > failing with the following error:
> > 
> > AssertionError: In state 'chrome_user_installed_not_inuse', Registry key
> > HKEY_LOCAL_MACHINE\Software\Chromium exists.
> > 
> > This is most likely due to the change I made in change 2086353 to delete
> > a value instead of the key.
> > 
> > Now the test will delete the key if the test is the one that created the
> > key in the first place.
> > 
> > Bug: 1059314
> > Change-Id: I2b85e1f4c979c52a41aebb41c4951b60cf58a50a
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2092939
> > Commit-Queue: Greg Thompson <grt@chromium.org>
> > Reviewed-by: Greg Thompson <grt@chromium.org>
> > Auto-Submit: S. Ganesh <ganesh@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#748062}
> 
> TBR=ganesh@chromium.org,grt@chromium.org
> 
> Change-Id: I875c730322f5bc4cc9fdfa8b5497e26f2b8b81da
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 1059314
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2095201
> Reviewed-by: Scott Violet <sky@chromium.org>
> Commit-Queue: Scott Violet <sky@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#748256}

TBR=sky@chromium.org,ganesh@chromium.org,grt@chromium.org

Change-Id: Ia53b0dae159068f44137e0e8d597d3dd9c2f0428
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1059314
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2095766
Reviewed-by: S. Ganesh <ganesh@chromium.org>
Commit-Queue: S. Ganesh <ganesh@chromium.org>
Cr-Commit-Position: refs/heads/master@{#748415}