ensure_gn_version.py: fix exception printing
Not all exceptions have a |msg| member leading to crashes like:

Force-installing 972ed755f8e6d31cae9ba15fcd08136ae1a7886f to update it.
Traceback (most recent call last):
  File "src/buildtools/ensure_gn_version.py", line 116, in <module>
    sys.exit(main())
  File "src/buildtools/ensure_gn_version.py", line 99, in main
    print('Failed to extract the binary:\n%s\n' % e.msg)
AttributeError: 'exceptions.IOError' object has no attribute 'msg'
Error: Command '/usr/bin/python src/buildtools/ensure_gn_version.py git_revision:972ed755f8e6d31cae9ba15fcd08136ae1a7886f'
       returned non-zero exit status 1 in /usr/local/src/chromium

Let Python stringify the entire exception as it should DTRT all the
time.  Here we now get:
Force-installing 972ed755f8e6d31cae9ba15fcd08136ae1a7886f to update it.
Failed to extract the binary:
[Errno 13] Permission denied: '/usr/local/src/chromium/src/buildtools/linux64/gn'

Similarly, not all exceptions fill out the |message| member.
If the tool doesn't exist, subprocess fails with OSError (ENOENT),
and the message string is empty.  So rely on stringifying the whole
exception to get something useful out:
  `/usr/local/src/chromium/src/buildtools/linux64/gn --version` failed:
  [Errno 2] No such file or directory

Change-Id: I878e2d2d9b8933743b3e3a632b2e65bc9a0b5724
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1697946
Auto-Submit: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Dirk Pranke <dpranke@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Cr-Commit-Position: refs/heads/master@{#676633}