rc.py: Python 3 regex fix
preprocessed_output is a bytes-like object, so the re.sub() arguments need to be bytestrings too.

Traceback (most recent call last):
  File "C:\Google\chromium\src\build\toolchain\win\rc\rc.py", line 265, in <module>
    sys.exit(main())
  File "C:\Google\chromium\src\build\toolchain\win\rc\rc.py", line 259, in main
    rc_exe_exit_code = CompareToMsRcOutput(preprocessed_output, is_utf8, flags)
  File "C:\Google\chromium\src\build\toolchain\win\rc\rc.py", line 201, in CompareToMsRcOutput
    preprocessed_output = re.sub(rb'^#.*$', '', preprocessed_output, flags=re.M)
  File "C:\Program Files\Python38\lib\re.py", line 208, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 0: expected a bytes-like object, str found

Bug: 941669
Change-Id: I0acf39394fa3a7d263108e3d5ce7c88d9f8c6d7b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1995334
Reviewed-by: Scott Graham <scottmg@chromium.org>
Reviewed-by: Nico Weber <thakis@chromium.org>
Commit-Queue: Raul Tambre <raul@tambre.ee>
Auto-Submit: Raul Tambre <raul@tambre.ee>
Cr-Commit-Position: refs/heads/master@{#730585}