browser_switcher: Use std::unique_ptr instead of std::auto_ptr
std::auto_ptr is deprecated since C++11 and removed in C++17.
Fortunately the strange behaviour of std::auto_ptr isn't used here and we can simply replace it with std::unique_ptr.

../../chrome/browser/browser_switcher/bho/browser_switcher_core.cc(502,8): error: no member named 'auto_ptr' in namespace 'std'
  std::auto_ptr<wchar_t> buffer(new wchar_t[length]);
  ~~~~~^
../../chrome/browser/browser_switcher/bho/browser_switcher_core.cc(543,8): error: no member named 'auto_ptr' in namespace 'std'
  std::auto_ptr<wchar_t> sanitized_url(new wchar_t[url.length() * 3 + 1]);
  ~~~~~^
../../chrome/browser/browser_switcher/bho/browser_switcher_core.cc(616,8): error: no member named 'auto_ptr' in namespace 'std'
  std::auto_ptr<wchar_t> browser_path(new wchar_t[length]);
  ~~~~~^
../../chrome/browser/browser_switcher/bho/browser_switcher_core.cc(635,10): error: no member named 'auto_ptr' in namespace 'std'
    std::auto_ptr<wchar_t> expanded_path(new wchar_t[expanded_size + 2]);
    ~~~~~^

Bug: 752720
Change-Id: I040bd8412aebebeadfd70008930fbe457f9b8b37
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2124568
Auto-Submit: Raul Tambre <raul@tambre.ee>
Commit-Queue: Nicolas Ouellet-Payeur <nicolaso@chromium.org>
Reviewed-by: Nicolas Ouellet-Payeur <nicolaso@chromium.org>
Cr-Commit-Position: refs/heads/master@{#754454}