bindings: Fix implicit list in list comprehension
Python 2 seems to implicitly create a list in some cases.
Python 3 doesn't do that. Surround with brackets to make this explicit, so it works on both.

  File "../../third_party/blink/renderer/bindings/scripts/generate_global_constructors.py", line 123
    for name in 'RuntimeEnabled', 'ContextEnabled', 'SecureContext'
                                ^
SyntaxError: invalid syntax

Bug: 941669
Change-Id: I1043faf33eab77fc220072b2e575182b4a015ecd
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2124755
Auto-Submit: Raul Tambre <raul@tambre.ee>
Commit-Queue: Yuki Shiino <yukishiino@chromium.org>
Reviewed-by: Yuki Shiino <yukishiino@chromium.org>
Cr-Commit-Position: refs/heads/master@{#754400}