Revert "Cleanup: Remove base/file_util.h. Convert remaining references."
Appears this may have led to a broken build:
chrome_webrtc_simulcast_browsertest.cc:6:10: fatal error: 'base/file_util.h' file not found
Reverting on branch only

This reverts commit 6d63c4898c2da5a286d01f80229baeb914f99f18.