Revert "[base] Remove implicit-destination PostTask"
This reverts commit 50b3e1fd102788ea5d3858ecfaaaceefa7c25582.

Reason for revert: crbug.com/1090992 Compile failures:

FAILED: obj/chrome/browser/browser/recovery_component_installer.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
../../chrome/browser/component_updater/recovery_component_installer.cc:419:3: error: too few arguments to function call, expected 3, have 2; did you mean 'base::ThreadPool::PostTask'?
base::PostTask(FROM_HERE, base::BindOnce(std::move(callback), result));
^~~~
base::ThreadPool::PostTask
../../base/task/thread_pool.h:95:15: note: 'base::ThreadPool::PostTask' declared here
static bool PostTask(const Location& from_here, OnceClosure task);
^

Original change's description:
> [base] Remove implicit-destination PostTask
> 
> No TaskTraits implcitly meant base::ThreadPool. The migration away
> from this paradigm is complete (task APIs v3 is bringing explicit
> API-as-destination). Remove this right away before we're ready to
> completely remove post_task.h to avoid the addition of new callers
> without an explicit destination.
> 
> Bug: 968047, 1026641
> Change-Id: I54d04872498d340cfd8ec02aa88b3e9cba1a7547
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2225541
> Commit-Queue: Gabriel Charette <gab@chromium.org>
> Reviewed-by: Sami Kyöstilä <skyostil@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#774758}

TBR=gab@chromium.org,skyostil@chromium.org

Change-Id: Ia6e764cf3293ef9ac789ce6f173951ab8e4736fe
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 968047, 1026641, 1090992
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2229410
Reviewed-by: Dominic Mazzoni <dmazzoni@chromium.org>
Commit-Queue: Dominic Mazzoni <dmazzoni@chromium.org>
Cr-Commit-Position: refs/heads/master@{#774796}