Add //third_party/blink/public/common/privacy_budget:privacy_budget to third_party/blink/common/privacy_budget/privacy_budget deps.
The missing dependency causes flaky compile failure. E.g.
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8877912291953186800/+/steps/compile/0/stdout
In file included from ../../third_party/blink/common/privacy_budget/identifiability_metric_builder.cc:5:
../../third_party/blink/public/common/privacy_budget/identifiability_metric_builder.h:16:10: fatal error: 'third_party/blink/public/mojom/web_feature/web_feature.mojom-forward.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         1 error generated.

Change-Id: I1341844ccf5ed4e7c496fa60125204b67e631ab6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2239129
Commit-Queue: Kentaro Hara <haraken@chromium.org>
Auto-Submit: Takashi Sakamoto <tasak@google.com>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Cr-Commit-Position: refs/heads/master@{#776879}