[Sheriff] Revert "Roll src/third_party/devtools-frontend/src 29c52f9cafce..4665866ae8db (4 commits)"
This reverts commit dee355ffefa9a2f46695077eebdb73ca4fab9f4e.

Reason for revert: Speculative fix for build breakage which mentions
typescript:
Traceback (most recent call last):
  File "../../third_party/devtools-frontend/src/third_party/typescript/ts_library.py", line 113, in <module>
    sys.exit(main())
  File "../../third_party/devtools-frontend/src/third_party/typescript/ts_library.py", line 90, in main
    copy_all_typescript_sources(sources, path.dirname(tsconfig_output_location))
  File "../../third_party/devtools-frontend/src/third_party/typescript/ts_library.py", line 109, in copy_all_typescript_sources
    shutil.copy(generated_javascript_location, dest)
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/shutil.py", line 139, in copy
    copyfile(src, dst)
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/b/s/w/ir/cache/builder/src/out/Debug/resources/inspector/formatter_worker/FormattedContentBuilder_test.js'

Original change's description:
> Roll src/third_party/devtools-frontend/src 29c52f9cafce..4665866ae8db (4 commits)
> 
> https://chromium.googlesource.com/devtools/devtools-frontend.git/+log/29c52f9cafce..4665866ae8db
> 
> git log 29c52f9cafce..4665866ae8db --date=short --first-parent --format='%ad %ae %s'
> 2020-02-27 jacktfranklin@chromium.org Typescriptify FormattedContentBuilder + move tests
> 2020-02-27 kahinds@microsoft.com Remove transparent border-top from Elements tree rows
> 2020-02-27 tvanderlippe@chromium.org Run TypeScript without building mode
> 2020-02-27 jacktfranklin@chromium.org Update screenshot testing to enable element screenshots
> 
> Created with:
>   gclient setdep -r src/third_party/devtools-frontend/src@4665866ae8db
> 
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/devtools-frontend-chromium
> Please CC devtools-waterfall-sheriff-onduty@grotations.appspotmail.com on the revert to ensure that a human
> is aware of the problem.
> 
> To report a problem with the AutoRoller itself, please file a bug:
> https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
> 
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+/master/autoroll/README.md
> 
> Bug: chromium:1011811,chromium:1048378,chromium:1051458
> Tbr: devtools-waterfall-sheriff-onduty@grotations.appspotmail.com
> Change-Id: I256e61998f62ceac547d1f7c42dbed56f70ff533
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2078606
> Reviewed-by: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/master@{#745197}

TBR=chromium-autoroll@skia-public.iam.gserviceaccount.com,devtools-waterfall-sheriff-onduty@grotations.appspotmail.com

Change-Id: Ic7cdfe15a103c24a23f5620e572350e50217860e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: chromium:1011811, chromium:1048378, chromium:1051458
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2079381
Reviewed-by: Katie Dektar <katie@chromium.org>
Commit-Queue: Katie Dektar <katie@chromium.org>
Cr-Commit-Position: refs/heads/master@{#745221}