Fix Clank official build failure. Speculatively revert CL.
Clank Official Build Failure:
~~~
  File "../../build/android/gyp/apkbuilder.py", line 383, in <module>
    main(sys.argv[1:])
  File "../../build/android/gyp/apkbuilder.py", line 307, in main
    with zipfile.ZipFile(options.dex_file, 'r') as dex_zip:
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 857, in _RealGetContents
    x._decodeExtra()
  File "/usr/lib/python2.7/zipfile.py", line 388, in _decodeExtra
    tp, ln = unpack('<HH', extra[:4])
struct.error: unpack requires a string argument of length 4
~~~

This CL speculatively revert the CLs that seems to be linked with build
failure.

The bug happens while trying to zip dex file:
~~~
with zipfile.ZipFile(options.dex_file, 'r') as dex_zip:
~~~
and the following branch of CL deals with zip + dex files:

Revert "dex.py: Remove obsolete flags, code clean-up."
  commit 35fc212eb07565366d933afed0543590d929aa6a.
  https://chromium-review.googlesource.com/c/chromium/src/+/1694090/4
Revert "Android: Zipalign library dex files for incremental install"
  commit 209eac2379a6b74b6576dc4d01cb2af0f86ce843.
  https://chromium-review.googlesource.com/c/chromium/src/+/1692492/6

TBR=agrieve@chromium.org

(cherry picked from commit ab83ee3cb8a84be2a0de7a2b908cdaada2cd35fc)

Bug: 983519
Change-Id: Ia90b7f5d16b09ae29cf0617a09a80e5312ed858a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1700064
Commit-Queue: Arthur Sonzogni <arthursonzogni@chromium.org>
Reviewed-by: Sam Maier <smaier@chromium.org>
Reviewed-by: Arthur Sonzogni <arthursonzogni@chromium.org>
Auto-Submit: Arthur Sonzogni <arthursonzogni@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#676898}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1701947
Reviewed-by: Ben Mason <benmason@chromium.org>
Cr-Commit-Position: refs/branch-heads/3851@{#4}
Cr-Branched-From: 2193531e15662435668b9f567875b5d12cdfb74a-refs/heads/master@{#676687}