Revert "[mojo] Remove DocumentInterfaceBroker"
This reverts commit 3e01d61b6274c4c9d6580f964291c2a5de97a733.

Reason for revert: Caused build failure
https://ci.chromium.org/p/chromium/builders/ci/linux-archive-dbg/5699

[56914/72140] CXX obj/content/test/content_browsertests/render_frame_impl_browsertest.o
FAILED: obj/content/test/content_browsertests/render_frame_impl_browsertest.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
../../content/renderer/render_frame_impl_browsertest.cc:50:10: fatal error: 'third_party/blink/public/mojom/frame/frame_host_test_interface.mojom.h' file not found
#include "third_party/blink/public/mojom/frame/frame_host_test_interface.mojom.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.


Original change's description:
> [mojo] Remove DocumentInterfaceBroker
> 
> This change removes the DocumentInterfaceBroker mojom interface and all
> related plumbing. No functional changes since the interface was not used
> by anything (clients migrated to BrowserInterfaceBroker).
> 
> TBR=tommycli@chromium.org,rbpotter@chromium.org,arthursonzogni@chromium.org,kenrb@chromium.org,alexmos@chromium.org,rdevlin.cronin@chromium.org,haraken@chromium.org
> 
> Bug: 985120
> Change-Id: I893f940bc2c5d237aac5fb6b3962c06bfa98e938
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1881394
> Reviewed-by: Oksana Zhuravlova <oksamyt@chromium.org>
> Reviewed-by: Tommy Li <tommycli@chromium.org>
> Reviewed-by: Devlin <rdevlin.cronin@chromium.org>
> Reviewed-by: Alex Moshchuk <alexmos@chromium.org>
> Reviewed-by: Kentaro Hara <haraken@chromium.org>
> Reviewed-by: Chrome Cunningham <chcunningham@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Reviewed-by: Arthur Sonzogni <arthursonzogni@chromium.org>
> Reviewed-by: Rebekah Potter <rbpotter@chromium.org>
> Commit-Queue: Oksana Zhuravlova <oksamyt@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#713278}

TBR=dcheng@chromium.org,kenrb@chromium.org,tommycli@chromium.org,rdevlin.cronin@chromium.org,haraken@chromium.org,alexmos@chromium.org,chcunningham@chromium.org,rbpotter@chromium.org,arthursonzogni@chromium.org,oksamyt@chromium.org

Change-Id: I6c25e96111dca691e007353a27710251b125659e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 985120
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1902181
Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
Commit-Queue: Tsuyoshi Horo <horo@chromium.org>
Cr-Commit-Position: refs/heads/master@{#713294}