Revert "Convert services/media_session services to new Mojo types (6/n)"
This reverts commit b223de22ef9be4074b472ba79ffeaf2294852a81.

Reason for revert: Breaks branded Chrome OS build:
../../chromeos/services/assistant/media_session/assistant_media_session.cc:144:28: error: no member named 'encountered_error' in 'mojo::Remote<media_session::mojom::AudioFocusManager>'
../../chromeos/services/assistant/media_session/assistant_media_session.cc:149:44: error: no member named 'BindNewPipeAndPassReceiver' in 'media_session::mojom::AudioFocusManagerProxy'
because of assistant_media_session.cc. Note that this file only
compiles with  gn arg is_chrome_branded = true. I think
audio_focus_remote_->BindNewPipeAndPassReceiver() has to be
audio_focus_remote_.BindNewPipeAndPassReceiver(), but I couldn't
figure out how to fix encountered_error(). See also
https://chromium-review.googlesource.com/c/chromium/src/+/1725553

Original change's description:
> Convert services/media_session services to new Mojo types (6/n)
>
> The primary goal of this CL is to convert usage of |functions| of
> interface AudioFocusManager and port dependent files to adopt new
> implementation.
>
> Bug: 955171
> Change-Id: I2c8f269b2b36034b9ebc5beb1aef56ee3db691b1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1715367
> Commit-Queue: Abhijeet Kandalkar <abhijeet@igalia.com>
> Reviewed-by: Kinuko Yasuda <kinuko@chromium.org>
> Reviewed-by: Ken Rockot <rockot@google.com>
> Reviewed-by: Mitsuru Oshima <oshima@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#682154}

TBR=oshima@chromium.org,kinuko@chromium.org,rockot@google.com,abhijeet@igalia.com

Change-Id: Ie5a8b1652ddf623b21a903334713944122013e15
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 955171, 988971
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1725890
Commit-Queue: Lutz Justen <ljusten@chromium.org>
Reviewed-by: Lutz Justen <ljusten@chromium.org>
Cr-Commit-Position: refs/heads/master@{#682236}