json5_generator: Fix Python 3 dictionary usage
iteritems() was removed in Python 3. items() does the same on both.

Traceback (most recent call last):
  File "../../third_party/blink/renderer/build/scripts/make_feature_policy_helper.py", line 79, in <module>
    json5_generator.Maker(FeaturePolicyFeatureWriter).main()
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\json5_generator.py", line 337, in main
    writer = self._writer_class(args.files, args.output_dir)
  File "../../third_party/blink/renderer/build/scripts/make_feature_policy_helper.py", line 15, in __init__
    super(FeaturePolicyFeatureWriter, self).__init__(
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\json5_generator.py", line 276, in __init__
    self.json5_file = Json5File.load_from_files(
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\json5_generator.py", line 140, in load_from_files
    return Json5File(file_paths, merged_doc, default_metadata,
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\json5_generator.py", line 124, in __init__
    self._process(doc)
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\json5_generator.py", line 155, in _process
    entry = self._get_entry(item)
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\json5_generator.py", line 197, in _get_entry
    self._validate_parameter(self.parameters[key], value)
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\json5_generator.py", line 218, in _validate_parameter
    elif not _is_valid(valid_values, value, valid_keys):
  File "C:\Google\chromium\src\third_party\blink\renderer\build\scripts\json5_generator.py", line 106, in _is_valid
    for key, val in value.iteritems()])
AttributeError: 'dict' object has no attribute 'iteritems'

Bug: 941669
Change-Id: I5a60c0b54584a743ec86e51902e061af08c59c8b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2093213
Auto-Submit: Raul Tambre <raul@tambre.ee>
Commit-Queue: Kent Tamura <tkent@chromium.org>
Reviewed-by: Kent Tamura <tkent@chromium.org>
Cr-Commit-Position: refs/heads/master@{#748069}