Reland "IDN Display: Add whole-script-confusable characters for Greek"
This reverts commit c03d2408c8daa8fed19065376353c17d2a0d612b.

Reason for revert: Test with change still failed
https://ci.chromium.org/p/chromium/builders/ci/Win7%20Tests%20%281%29/98664

Original change's description:
> Revert "IDN Display: Add whole-script-confusable characters for Greek"
> 
> This reverts commit de165b667d781d28f311981108270f61a59e7511.
> 
> Reason for revert: Potentially implicated for browser_tests ErrorPageForIDNTest.IDN failure
> 
> First failing run
> https://ci.chromium.org/p/chromium/builders/ci/Win10%20Tests%20x64/43723
> 
> [ RUN      ] ErrorPageForIDNTest.IDN
> ../../chrome/browser/net/errorpage_browsertest.cc(1443): error: Value of: IsDisplayingText(browser(), kHostnameJSUnicode)
>   Actual: false
> Expected: true
> 
> Original change's description:
> > IDN Display: Add whole-script-confusable characters for Greek
> > 
> > This CL adds a list of Greek characters that look like Latin
> > characters. A domain consisting only of these characters and not
> > having a .gr ccTLD or other Greek TLDs such as .ελ will be
> > converted to punycode, as is done for other
> > whole-script-confusables such as Cyrillic and Hebrew.
> > 
> > Bug: 722167
> > Change-Id: Id0157503c605a6a73eb49147c26b48d5995d1ff2
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1986209
> > Commit-Queue: Mustafa Emre Acer <meacer@chromium.org>
> > Reviewed-by: Joe DeBlasio <jdeblasio@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#728697}
> 
> TBR=meacer@chromium.org,jdeblasio@chromium.org
> 
> Change-Id: I01408fe8791d50ce10feeb7656bfd72b9cea105d
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 722167
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1989297
> Reviewed-by: Robert Liao <robliao@chromium.org>
> Commit-Queue: Robert Liao <robliao@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#728827}

TBR=meacer@chromium.org,robliao@chromium.org,jdeblasio@chromium.org

Change-Id: Ib745a6fe985d527c6c89dae599547a43dbf34a9f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 722167
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1989427
Reviewed-by: Robert Liao <robliao@chromium.org>
Commit-Queue: Robert Liao <robliao@chromium.org>
Cr-Commit-Position: refs/heads/master@{#728845}