Revert "[Lockscreen Media Controls] Media controls layout modification."
This reverts commit 7c25fdeb10b798a804773affa97236405258a804.

Reason for revert:
Broke the M79 branch build for linux-chromeos with these errors:

../../ash/login/ui/lock_screen_media_controls_view.cc:168:13: error: incomplete type 'ash::AshColorProvider' named in nested name specifier
            AshColorProvider::AshColorMode::kDark));
            ^~~~~~~~~~~~~~~~~~
../../ash/shell.h:105:7: note: forward declaration of 'ash::AshColorProvider'
class AshColorProvider;
Revert "[Lockscreen Media Controls] Media controls layout modification."
      ^
../../ash/login/ui/lock_screen_media_controls_view.cc:225:7: error: use of undeclared identifier 'kMediaControlsBackground'
      kMediaControlsBackground, kMediaControlsCornerRadius));
      ^

I also reverted https://chromium-review.googlesource.com/c/chromium/src/+/1846729

Original change's description:
> [Lockscreen Media Controls] Media controls layout modification.
> 
> Update lock screen media controls layout and icons.
> 
> (cherry picked from commit 8363b89128f985ac4dfeb5c21d6decf1562e5261)
> 
> Bug: 1015133
> Change-Id: I288f4826e490c18d40217ddbfd4305b25fd8c514
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1865717
> Reviewed-by: Evan Stade <estade@chromium.org>
> Reviewed-by: Xiyuan Xia <xiyuan@chromium.org>
> Reviewed-by: Tommy Steimel <steimel@chromium.org>
> Commit-Queue: Jazz Xu <jazzhsu@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#707402}
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1879746
> Reviewed-by: Jazz Xu <jazzhsu@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3945@{#134}
> Cr-Branched-From: e4635fff7defbae0f9c29e798349f6fc0cce4b1b-refs/heads/master@{#706915}

TBR=jazzhsu@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 1015133
Change-Id: I29c42c8ffa06b33e4073351c59e73f605deb05a5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1882165
Reviewed-by: James Cook <jamescook@chromium.org>
Cr-Commit-Position: refs/branch-heads/3945@{#206}
Cr-Branched-From: e4635fff7defbae0f9c29e798349f6fc0cce4b1b-refs/heads/master@{#706915}