Revert "Tune the UI Automation content view"
This reverts commit e2c6d84a14e7033c2e176bc9d202730a5761554d.

Reason for revert:
DumpAccessibilityTreeTest.AccessibilityButtonNameCalc/uia is failing on all Windows 7 waterfall bots:
https://test-results.appspot.com/dashboards/flakiness_dashboard.html#testType=content_browsertests&tests=DumpAccessibilityTreeTest.AccessibilityButtonNameCalc%2Fuia

[4176:1936:1212/164612.912:ERROR:dump_accessibility_test_helper.cc(126)] Diff:
* Line Expected
- ---- --------
     1 document
     2 ++button Name='InnerText0'
     3 ++button Name='InnerText1'
     4 ++button Name='AriaLabel2'
     5 ++button Name='LabelledBy3'
     6 ++button Name='LabelledBy4'
     7 ++button Name='InnerText5'
     8 ++button Name='Outer inner'
     9 ++++description Name='Outer' IsControlElement=false
*   10 ++++group
    11 ++++++description Name='inner' IsControlElement=false
    12 ++button Name='Outer inner1'
    13 ++++description Name='Outer' IsControlElement=false
    14 ++++group Name='inner1'
    15 ++++++description Name='inner2' IsControlElement=false
    16 ++button Name='Outer grandchild'
    17 ++++description Name='Outer' IsControlElement=false
    18 ++++group
*   19 ++++++group
    20 ++++++++description Name='grandchild' IsControlElement=false
    21 <-- End-of-file -->

Actual
------
document
++button Name='InnerText0'
++button Name='InnerText1'
++button Name='AriaLabel2'
++button Name='LabelledBy3'
++button Name='LabelledBy4'
++button Name='InnerText5'
++button Name='Outer inner'
++++description Name='Outer' IsControlElement=false
++++group IsControlElement=false
++++++description Name='inner' IsControlElement=false
++button Name='Outer inner1'
++++description Name='Outer' IsControlElement=false
++++group Name='inner1'
++++++description Name='inner2' IsControlElement=false
++button Name='Outer grandchild'
++++description Name='Outer' IsControlElement=false
++++group
++++++group IsControlElement=false
++++++++description Name='grandchild' IsControlElement=false
<-- End-of-file -->
../../content/browser/accessibility/dump_accessibility_browsertest_base.cc(436): error: Value of: matches_expectation
  Actual: false
Expected: true


Original change's description:
> Tune the UI Automation content view
> 
> In testing we've observed scenarios where uninteresting container nodes
> in the accessibility tree have caused issues with Narrator. This CL
> removes some of these containers from the UI Automation content view,
> which is the view Narrator uses.
> 
> Bug: 1031302
> Change-Id: Iaee82c3add61659b9c14591d072ab49b069f5c61
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1938308
> Commit-Queue: Adam Ettenberger <adettenb@microsoft.com>
> Reviewed-by: Robert Sesek <rsesek@chromium.org>
> Reviewed-by: Kentaro Hara <haraken@chromium.org>
> Reviewed-by: Nektarios Paisios <nektar@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#724335}

TBR=haraken@chromium.org,nektar@chromium.org,rsesek@chromium.org,kbabbitt@microsoft.com,kschmi@microsoft.com,adettenb@microsoft.com

Change-Id: I3159634c2c234e95c48bf6d120ef5fae2c81b05d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1031302
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1965745
Reviewed-by: Alan Cutter <alancutter@chromium.org>
Commit-Queue: Alan Cutter <alancutter@chromium.org>
Cr-Commit-Position: refs/heads/master@{#724528}