Merge Reland "Dynamically update cookies link row label based on cookie setting." into M-82.
Bug for merge request: 1061986

This reverts commit e304bfb93851f2142319de00edcfa041d9a493eb.

Reason for revert: Fixed failing test that was not setting the state of the PrivacySettingsRedesign flag and didn't call the setup function.

Original change's description:
> Revert "Dynamically update cookies link row label based on cookie setting."
>
> This reverts commit c3a9401549ef09573cde7401e70b2acf48a3633b.
>
> Reason for revert: Flakily failing on all platforms:
> https://ci.chromium.org/p/chromium/builders/ci/Linux%20Tests/88090
> [27939:27939:0312/140853.144376:ERROR:CONSOLE(49)] "Mocha test failed: SiteSettingsPage CookiesLinkRowSublabel
> AssertionError: expected 'Allow sites to save and read cookie data' to equal undefined
>     at Function.assert.strictEqual (file:///b/s/w/ir/third_party/chaijs/chai.js:2329:32)
>     at assertEquals (file:///b/s/w/ir/chrome/test/data/webui/test_api.js:699:15)
>     at Context.<anonymous> (file:///b/s/w/ir/chrome/test/data/webui/settings/site_settings_page_test.js:74:5)
> Bug: 1061249
>
> Original change's description:
> > Dynamically update cookies link row label based on cookie setting.
> >
> > Previously link rows for content settings displayed one of two labels
> > describing their current setting. This CL extends the capability of
> > the cookies link rows specifically to express one of the four possible
> > effective cookie settings.
> >     -Allow
> >     -Block Third Party only in Incognito
> >     -Block Third Party
> >     -Block
> >
> > To ensure that this label remains correct across both the preference
> > and content settings changes that affect the effective cookie setting,
> > an additional WebUI listener is created which pushes updates to JS
> > for immediate display.
> >
> > This updated label is applied to both cookies link row locations
> > when the privacySettingsRedesign flag is enabled, and applied to
> > neither when it is disabled.
> >
> > Bug: 1032584
> > Change-Id: I11a984bce60878b6224506bfc1cd1a5cf3a2e63e
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2095925
> > Commit-Queue: Theodore Olsauskas-Warren <sauski@google.com>
> > Reviewed-by: dpapad <dpapad@chromium.org>
> > Reviewed-by: Martin Šrámek <msramek@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#749510}
>
>
>
> Change-Id: I43acd7240282ed62e20f2321cd53bf6f2963d45a
> No-Presubmit: true
> No-Tree-Checks: true
> Bug: 1032584
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2101389
> Reviewed-by: Alan Cutter <alancutter@chromium.org>
> Commit-Queue: Alan Cutter <alancutter@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#749986}

(cherry picked from commit cfd812ceb66b11a64385dd5697a74806c2b14fad)

Bug: 1061249, 1032584, 1061986
Change-Id: I43c594b28228720a5383587eee81aba24d2e1db0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2103508
Reviewed-by: dpapad <dpapad@chromium.org>
Commit-Queue: Sean Harrison <harrisonsean@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#750373}
TBR: msramek@chromium.org
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2106343
Reviewed-by: Martin Šrámek <msramek@chromium.org>
Reviewed-by: Sean Harrison <harrisonsean@chromium.org>
Cr-Commit-Position: refs/branch-heads/4085@{#41}
Cr-Branched-From: 938fda43077d4622c5b88984608d6becd5ebbb82-refs/heads/master@{#749737}