browser_switcher: Add missing noexcept specifier
A missing noexcept specifier is an error when compiling in C++17 mode.
STDMETHOD adds one, but we're missing it in the implementation.

../../chrome/browser/browser_switcher/bho/bho.cc(41,35): error: 'SetSite' is missing exception specification '__attribute__((nothrow))' [-Werror,-Wmicrosoft-exception-spec]
STDMETHODIMP CBrowserSwitcherBHO::SetSite(IUnknown* site) {
                                  ^
../..\chrome/browser/browser_switcher/bho/bho.h(53,13): note: previous declaration is here
  STDMETHOD(SetSite)(IUnknown* site);
            ^

Bug: 752720
Change-Id: I1cfe0c27a9caeb6b450c752a721a7532d872567a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2124709
Auto-Submit: Raul Tambre <raul@tambre.ee>
Commit-Queue: Nicolas Ouellet-Payeur <nicolaso@chromium.org>
Reviewed-by: Nicolas Ouellet-Payeur <nicolaso@chromium.org>
Cr-Commit-Position: refs/heads/master@{#754451}