Revert "Remove gray titlebar separator line from Chrome OS PWA windows"
This reverts commit 3dad694738b80522d5cd54303c0b490e5d62ab4a.

Reason for revert: Breaks compile.
../../chrome/browser/ui/views/frame/browser_view_layout_unittest.cc:183:21: error: allocating an object of abstract class type '(anonymous namespace)::MockBrowserViewLayoutDelegate'
delegate_ = new MockBrowserViewLayoutDelegate();
^
../../chrome/browser/ui/views/frame/browser_view_layout_delegate.h:26:16: note: unimplemented pure virtual method 'IsContentsSeparatorEnabled' in 'MockBrowserViewLayoutDelegate'

Original change's description:
> Remove gray titlebar separator line from Chrome OS PWA windows
> 
> This CL makes the contents separator line conditional on whether the
> browser window is for a PWA or not.
> This line was accidentally added to PWA windows by:
> https://chromium-review.googlesource.com/c/chromium/src/+/1845600
> 
> Before:
> https://bugs.chromium.org/p/chromium/issues/attachment?aid=418318&signed_aid=qDxxx-0Dy7v7DRzG1X2IKw==&inline=1
> 
> After:
> https://bugs.chromium.org/p/chromium/issues/attachment?aid=418319&signed_aid=foBwMWJfjX_2Kp905p0F6Q==&inline=1
> 
> 
> This issue seems to only affect Chrome OS as other platforms happen to
> position the separator line behind the web contents area:
> https://bugs.chromium.org/p/chromium/issues/attachment?aid=418333&signed_aid=Yca--FaV3JB8AIOY8YuyYA==&inline=1
> 
> 
> (cherry picked from commit b817cf40dee4ec78b83b9e985246996daba5bbdf)
> 
> Bug: 1012979
> Change-Id: I0190e55862636354c63f6256bd55c2cf642db178
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1885147
> Auto-Submit: Alan Cutter <alancutter@chromium.org>
> Commit-Queue: Alan Cutter <alancutter@chromium.org>
> Reviewed-by: Peter Kasting <pkasting@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#710692}
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1895264
> Reviewed-by: Alan Cutter <alancutter@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3945@{#430}
> Cr-Branched-From: e4635fff7defbae0f9c29e798349f6fc0cce4b1b-refs/heads/master@{#706915}

TBR=alancutter@chromium.org

Change-Id: Id05fa76cc8a1e14372bd1a11ed55f2a63c2fe8a5
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1012979
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1895514
Reviewed-by: Krishna Govind <govind@chromium.org>
Cr-Commit-Position: refs/branch-heads/3945@{#457}
Cr-Branched-From: e4635fff7defbae0f9c29e798349f6fc0cce4b1b-refs/heads/master@{#706915}