Revert "Remove BluetoothTest::PlatformSupportsLowEnergy()"
This reverts commit ca4ccac9d3ddeebb24f557ef96bf3cd033783084.

Reason for revert: Suspect of causing consistent failure in Win7 Tests (1) bot.

First failure:
https://ci.chromium.org/p/chromium/builders/ci/Win7%20Tests%20%281%29/101716

device_unittests failed because of:
All/BluetoothRemoteGattCharacteristicTestWinrt.WriteRemoteCharacteristic/1
All/BluetoothRemoteGattCharacteristicTestWinrt.ReadRemoteCharacteristic_WritePending/1
All/BluetoothRemoteGattCharacteristicTestWinrt.RemoteCharacteristic_Nested_Read_Write/1
All/BluetoothTestWinrtOnly.ConstructFakeAdapterWithoutRadio/0
...46 more failure(s) (50 total)...


[ RUN      ] All/BluetoothRemoteGattCharacteristicTestWinrt.Notification_During_WriteRemoteCharacteristic/1
../../device/bluetooth/bluetooth_remote_gatt_characteristic_unittest.cc(1544): error: Expected equality of these values:
  notification_value
    Which is: { '\xDE' (222) }
  characteristic1_->GetValue()
    Which is: {}

Original change's description:
> Remove BluetoothTest::PlatformSupportsLowEnergy()
> 
> Remove BluetoothTest::PlatformSupportsLowEnergy() since it always
> returns true (all dead code hiding behind it is also removed).
> Note: BluetoothLowEnergyWrapper::IsBluetoothLowEnergySupported() is left
> as-is since it's still used, but no longer used
> BluetoothLowEnergyWrapperFake::IsBluetoothLowEnergySupported() is
> removed.
> 
> Bug: 971817
> Change-Id: I6d2b53bf6b840d3015a736c56a58055863ba6a3e
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2144190
> Reviewed-by: Ovidio de Jesús Ruiz-Henríquez <odejesush@chromium.org>
> Reviewed-by: Nina Satragno <nsatragno@chromium.org>
> Commit-Queue: Ovidio de Jesús Ruiz-Henríquez <odejesush@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#759318}

TBR=nsatragno@chromium.org,odejesush@chromium.org,bershanskiy@pm.me

Change-Id: I7ce54a52b9f4f3082ad2f5e168d829c972c91980
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 971817
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2151566
Reviewed-by: Guido Urdaneta <guidou@chromium.org>
Commit-Queue: Guido Urdaneta <guidou@chromium.org>
Cr-Commit-Position: refs/heads/master@{#759556}