Revert "ambient: Add Get/Update Settings APIs"
This reverts commit e77cef6b8f8d11ac5404ad5f75d7461e1e2f590b.

Reason for revert: photo_client_impl.cc fails to build on internal builds
../../chrome/browser/ui/ash/ambient/backdrop/photo_client_impl.cc:213:31: error: no member named 'CreateFetchTopicInfoRequest' in 'chromeos::ambient::BackdropClientConfig'; did you mean 'GetFetchTopicInfoRequest'?
      backdrop_client_config_.CreateFetchTopicInfoRequest(
https://ci.chromium.org/p/chrome/builders/ci/chromeos-eve-chrome/5876

Original change's description:
> ambient: Add Get/Update Settings APIs
> 
> This patch adds the Get/Update Settings APIs so that we can show and
> update it in the Chrome OS Settings ambient mode page, which will be
> implemented in a follow up cl.
> 
> Bug: b/148483925
> Test: manual
> Change-Id: Ia74d875813860a6abbfdc01479a67fed0c029fb8
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2125685
> Commit-Queue: Tao Wu <wutao@chromium.org>
> Reviewed-by: Xiaohui Chen <xiaohuic@chromium.org>
> Reviewed-by: Xiyuan Xia <xiyuan@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#755531}

TBR=xiyuan@chromium.org,xiaohuic@chromium.org,wutao@chromium.org

Change-Id: I6cd788cbb13cb7f7fac6177e686881d239964b11
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: b/148483925
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2133228
Reviewed-by: Ben Pastene <bpastene@chromium.org>
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Cr-Commit-Position: refs/heads/master@{#755602}