Revert "Roll src/third_party/angle c3f57231124b..93bb092f88c9 (2 commits)"
This reverts commit 824a86d4f1bd8dafaf2d0f6be312d029c55d87c1.

Reason for revert: causes compile failure on Linux CFI bot.

Sample build: https://ci.chromium.org/p/chromium/builders/ci/Linux%20CFI/14810

Sample log: https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8903575125463586160/+/steps/compile/0/stdout?format=raw

---
[1121/1363] CXX obj/third_party/angle/libANGLE_base/OverlayWidgets.o
FAILED: obj/third_party/angle/libANGLE_base/OverlayWidgets.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
In file included from ../../third_party/angle/src/libANGLE/OverlayWidgets.cpp:12:
In file included from ../../third_party/angle/src/libANGLE/Overlay.h:17:
../../third_party/angle/src/libANGLE/angletypes.h:553:12: error: 'gl::overlay::Widget' is not polymorphic
ASSERT(ANGLE_HAS_DYNAMIC_TYPE(DestT *, src));
^                               ~~~
../../third_party/angle/src/libANGLE/angletypes.h:543:48: note: expanded from macro 'ANGLE_HAS_DYNAMIC_TYPE'
---


Original change's description:
> Roll src/third_party/angle c3f57231124b..93bb092f88c9 (2 commits)
>
> https://chromium.googlesource.com/angle/angle.git/+log/c3f57231124b..93bb092f88c9
>
> git log c3f57231124b..93bb092f88c9 --date=short --no-merges --format='%ad %ae %s'
> 2019-08-31 syoussefi@chromium.org Fix build error
> 2019-08-31 syoussefi@chromium.org Vulkan: Debug overlay
>
> Created with:
>   gclient setdep -r src/third_party/angle@93bb092f88c9
>
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/angle-chromium-autoroll
> Please CC cwallez@chromium.org on the revert to ensure that a human
> is aware of the problem.
>
> To report a problem with the AutoRoller itself, please file a bug:
> https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
>
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+/master/autoroll/README.md
>
> CQ_INCLUDE_TRYBOTS=luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:win_optional_gpu_tests_rel
> TBR=cwallez@chromium.org
>
> Bug: None
> Change-Id: Ib95dca1bd877ad6ee70343b17d0e41d44e291b27
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1779493
> Reviewed-by: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/master@{#692365}

TBR=cwallez@chromium.org,chromium-autoroll@skia-public.iam.gserviceaccount.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: None
Change-Id: Ic64b483a2283453bbb35424f5acee743eedddf84
notry: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1778459
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#692400}