Revert "Roll AFDO from 84.0.4129.0_rc-r1-merged to 84.0.4130.0_rc-r1-merged"
This reverts commit e1e309ba9c1a207128d4d65b8dba7f7191a78b05.

Reason for revert: 

failed to run `gclient sync -D`
________ running 'vpython src/tools/download_optimization_profile.py --newest_state=src/chrome/android/profiles/newest.txt --local_state=src/chrome/android/profiles/local.txt --output_name=src/chrome/android/profiles/afdo.prof --gs_url_base=chromeos-prebuilt/afdo-job/llvm' in '/usr/local/google/home/tikuta/chromium'
Traceback (most recent call last):
  File "src/tools/download_optimization_profile.py", line 150, in <module>
    sys.exit(main())
  File "src/tools/download_optimization_profile.py", line 144, in main
    RetrieveProfile(up_to_date_profile, new_tmpfile, args.gs_url_base)
  File "src/tools/download_optimization_profile.py", line 83, in RetrieveProfile
    with contextlib.closing(urllib2.urlopen(gs_url)) as u:
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Error: Command 'vpython src/tools/download_optimization_profile.py --newest_state=src/chrome/android/profiles/newest.txt --local_state=src/chrome/android/profiles/local.txt --output_name=src/chrome/android/profiles/afdo.prof --gs_url_base=chromeos-prebuilt/afdo-job/llvm' returned non-zero exit status 1 in /usr/local/google/home/tikuta/chromium



Original change's description:
> Roll AFDO from 84.0.4129.0_rc-r1-merged to 84.0.4130.0_rc-r1-merged
> 
> This CL may cause a small binary size increase, roughly proportional
> to how long it's been since our last AFDO profile roll. For larger
> increases (around or exceeding 100KB), please file a bug against
> gbiv@chromium.org. Additional context: https://crbug.com/805539
> 
> Please note that, despite rolling to chrome/android, this profile is
> used for both Linux and Android.
> 
> If this roll has caused a breakage, revert this CL and stop the roller
> using the controls here:
> https://autoroll.skia.org/r/afdo-chromium-autoroll
> Please CC gbiv@chromium.org on the revert to ensure that a human
> is aware of the problem.
> 
> To report a problem with the AutoRoller itself, please file a bug:
> https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
> 
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+/master/autoroll/README.md
> 
> Tbr: gbiv@chromium.org
> Change-Id: Iee8b371325a840415bc5a37acb49fd9fbe2981e1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2173704
> Reviewed-by: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
> Cr-Commit-Position: refs/heads/master@{#764133}

TBR=gbiv@chromium.org,chromium-autoroll@skia-public.iam.gserviceaccount.com

Change-Id: I90c5f7057d3472663c28383ef6d16c96d9fb1e59
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2174094
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Cr-Commit-Position: refs/heads/master@{#764475}