Revert "Reland "[tools/perf] Add webview_cpu_usage metric""
This reverts commit a0061b0ec23c29565c84e37da5fc02f135810e5f.

Reason for revert:
core.tbmv3.run_tbmv3_metric_unittest.RunTbmv3MetricIntegrationTests.testRunAllTbmv3Metrics failing consistently on Mac 10.12 and 10.14.
First failing builds:
https://ci.chromium.org/p/chromium/builders/ci/Mac10.12%20Tests/34967
https://ci.chromium.org/p/chromium/builders/ci/Mac10.14%20Tests/5202

[31/34] core.tbmv3.run_tbmv3_metric_unittest.RunTbmv3MetricIntegrationTests.testRunAllTbmv3Metrics failed unexpectedly 0.1263s:
  JSON result created in file:///b/s/w/itO3eVZi/tmp4IMOXE/out.json
  JSON result created in file:///b/s/w/itO3eVZi/tmp4IMOXE/out.json
  JSON result created in file:///b/s/w/itO3eVZi/tmp4IMOXE/out.json
  JSON result created in file:///b/s/w/itO3eVZi/tmp4IMOXE/out.json
  JSON result created in file:///b/s/w/itO3eVZi/tmp4IMOXE/out.json
  No metric found in the output.
  No metric found in the output.
  Traceback (most recent call last):
    File "/b/s/w/ir/tools/perf/benchmarks/../core/tbmv3/run_tbmv3_metric_unittest.py", line 75, in testRunAllTbmv3Metrics
      '--outfile', self.outfile_path,
    File "/b/s/w/ir/tools/perf/benchmarks/../core/tbmv3/run_tbmv3_metric.py", line 53, in Main
      args.trace, args.metric)
    File "/b/s/w/ir/tools/perf/benchmarks/../core/tbmv3/trace_processor.py", line 206, in RunMetric
      trace_file,
    File "/b/s/w/ir/tools/perf/benchmarks/../core/tbmv3/trace_processor.py", line 68, in _RunTraceProcessor
      (' '.join(args), stderr))
  RuntimeError: Running trace processor failed. Command line:
  /b/s/w/ir/tools/perf/benchmarks/../core/perfetto_binary_roller/bin/trace_processor_shell --run-metrics /b/s/w/ir/tools/perf/core/tbmv3/metrics/webview_cpu_usage_metric.sql --metrics-output json /b/s/w/itO3eVZi/tmp4IMOXE/tmpE1snCL
  Stderr:
  
  Loading trace: 0.00 MB
  
  Loading trace: 0.00 MB
  [599.650] processor_shell.cc:1042 Trace loaded: 0.00 MB (0.0 MB/s)
  [599.659] processor_shell.cc:1088 Error when computing metrics: RUN_METRIC: Unknown filename provided

Original change's description:
> Reland "[tools/perf] Add webview_cpu_usage metric"
> 
> This is a reland of 5c76e821ec868d47adf00867ea42585b0ca5c1d4
> 
> The test failures that caused the revert have been fixed in
> https://r.android.com/1325791 and rolled into chromium in
> https://crrev.com/c/2236240.
> 
> Original change's description:
> > [tools/perf] Add webview_cpu_usage metric
> >
> > This change adds a metric that calculates the amount of time WebView
> > spends on different frequencies.
> >
> > Bug: b/157855323
> > Change-Id: Ibb1fa61cc2ba1479f2b76ef642dc03c64a9a14b5
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2231452
> > Reviewed-by: Mikhail Khokhlov <khokhlov@google.com>
> > Commit-Queue: Oksana Zhuravlova <oksamyt@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#775713}
> 
> Bug: b/157855323
> Change-Id: I45552ebb5b3ca49c05506495e16a7a20e02ade86
> TBR: khokhlov@google.com
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2236055
> Commit-Queue: Oksana Zhuravlova <oksamyt@chromium.org>
> Reviewed-by: Oksana Zhuravlova <oksamyt@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#776374}

TBR=oksamyt@chromium.org,khokhlov@google.com

Change-Id: Ia56628ab779acd6187026e02e4bb76fb6d0eb98e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: b/157855323
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2237210
Reviewed-by: Alan Cutter <alancutter@chromium.org>
Commit-Queue: Alan Cutter <alancutter@chromium.org>
Cr-Commit-Position: refs/heads/master@{#776430}