Remove variable shadowing in blink/css
In an effort to reduce or even ban variable shadowing, this renames a
couple of variables. I'm interested in prohibiting shadowing
because I think it might prevent potential jumbo problems.

The exact warnings this patch avoids are:

third_party/blink/renderer/core/css/css_selector_list.cc:185:19: error: declaration shadows a local variable [-Werror,-Wshadow]
  for (wtf_size_t i = 0; i < num_args; ++i) {
                  ^
third_party/blink/renderer/core/css/css_selector_list.cc:140:10: note: previous declaration is here
  size_t i = 0;
         ^
third_party/blink/renderer/core/css/properties/css_parsing_utils.cc:2312:21: error: declaration shadows a local variable [-Werror,-Wshadow]
      for (unsigned i = 0; i < 4; ++i)
                    ^
third_party/blink/renderer/core/css/properties/css_parsing_utils.cc:2294:12: note: previous declaration is here
  unsigned i = 0;
           ^
third_party/blink/renderer/core/css/properties/longhands/contain_custom.cc:34:16: error: declaration shadows a local variable [-Werror,-Wshadow]
    CSSValueID id = range.Peek().Id();
               ^
third_party/blink/renderer/core/css/properties/longhands/contain_custom.cc:19:14: note: previous declaration is here
  CSSValueID id = range.Peek().Id();
             ^
third_party/blink/renderer/core/css/properties/longhands/content_custom.cc:191:29: error: declaration shadows a local variable [-Werror,-Wshadow]
        const AtomicString& value = state.GetElement()->getAttribute(attr);
                            ^
third_party/blink/renderer/core/css/properties/longhands/content_custom.cc:135:42: note: previous declaration is here
                         const CSSValue& value) const {
                                         ^
third_party/blink/renderer/core/css/properties/longhands/webkit_text_emphasis_style_custom.cc:105:33: error: declaration shadows a local variable [-Werror,-Wshadow]
      const CSSIdentifierValue& value = ToCSSIdentifierValue(list.Item(i));
                                ^
third_party/blink/renderer/core/css/properties/longhands/webkit_text_emphasis_style_custom.cc:100:58: note: previous declaration is here
                                         const CSSValue& value) const {
                                                         ^
third_party/blink/renderer/core/css/resolver/css_variable_resolver.cc:123:25: error: declaration shadows a local variable [-Werror,-Wshadow]
    CSSParserTokenRange range(result.tokens);
                        ^
third_party/blink/renderer/core/css/resolver/css_variable_resolver.cc:111:25: note: previous declaration is here
    CSSParserTokenRange range,
                        ^
third_party/blink/renderer/core/css/resolver/style_builder_converter.cc:1312:21: error: declaration shadows a local variable [-Werror,-Wshadow]
    const CSSValue& value = value_list.Item(i);
                    ^
third_party/blink/renderer/core/css/resolver/style_builder_converter.cc:1297:70: note: previous declaration is here
                                                     const CSSValue& value) {
                                                                     ^
third_party/blink/renderer/core/css/selector_checker.cc:765:12: error: declaration shadows a local variable [-Werror,-Wshadow]
      bool result = true;
           ^
third_party/blink/renderer/core/css/selector_checker.cc:749:53: note: previous declaration is here
                                       MatchResult& result) const {
                                                    ^
third_party/blink/renderer/core/css/style_property_serializer.cc:96:9: error: declaration shadows a local variable [-Werror,-Wshadow]
    int index = property_set_->FindPropertyIndex(property_id);
        ^
third_party/blink/renderer/core/css/style_property_serializer.cc:87:14: note: previous declaration is here
    unsigned index) const {
             ^

Bug: 923510
Change-Id: I18ff4db537f64e70f37abf2682b19305eaa86f92
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1508261
Reviewed-by: Fredrik Söderquist <fs@opera.com>
Commit-Queue: Daniel Bratell <bratell@opera.com>
Cr-Commit-Position: refs/heads/master@{#638991}