Revert "cros: Update sync disconnect dialog for SplitSettingsSync"
This reverts commit 472b61b0a76ebb14fab3056e2144cf5c6dd4d179.

Reason for revert: This CL probably caused the failures of CrSettingsPeoplePageSyncAccountControlTest.All
The first failed build: https://ci.chromium.org/p/chromium/builders/ci/Linux%20Tests%20%28dbg%29%281%29/86751?blamelist=1#blamelist-tab

Test 'CrSettingsPeoplePageSyncAccountControlTest.All' completed with the following status(es): 'FAILURE','FAILURE'

Test 'CrSettingsPeoplePageSyncAccountControlTest.All' had the following logs when run:

================================================================================

[ RUN      ] CrSettingsPeoplePageSyncAccountControlTest.All
[18619:18619:0210/184737.873886:10428715594:ERROR:edid_parser.cc(102)] Too short EDID data: manufacturer id
[18619:18619:0210/184739.304554:INFO:content_main_runner_impl.cc(948)] Chrome is running in full browser mode.
[18619:18754:0210/184741.088128:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[18619:18754:0210/184741.088268:WARNING:property.cc(144)] DaemonVersion: GetAndBlock: failed.
[18619:18754:0210/184741.088784:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[18619:18754:0210/184741.089292:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[18619:18619:0210/184741.509719:WARNING:gaia_auth_fetcher.cc(989)] Could not reach Google Accounts servers: errno -11
[18619:18619:0210/184742.399987:WARNING:gaia_auth_fetcher.cc(989)] Could not reach Google Accounts servers: errno -11
[18619:18619:0210/184742.896965:WARNING:CONSOLE(0)] "HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.", source:  (0)
[18619:18619:0210/184744.965914:WARNING:gaia_auth_fetcher.cc(989)] Could not reach Google Accounts servers: errno -11
[18619:18619:0210/184746.311487:INFO:CONSOLE(1045)] "Running TestCase CrSettingsPeoplePageSyncAccountControlTest.All", source: file:///b/s/w/ir/chrome/test/data/webui/test_api.js (1045)
[18619:18619:0210/184748.205791:ERROR:CONSOLE(49)] "Mocha test failed: SyncAccountControl not signed in and no stored accounts
Error: Uncaught TypeError: this.syncBrowserProxy_.turnOnSync is not a function (chrome://settings/people_page/sync_account_control.js:413)
    at Context.<anonymous> (file:///b/s/w/ir/chrome/test/data/webui/settings/sync_account_control_test.js:123:34)
", source: file:///b/s/w/ir/chrome/test/data/webui/mocha_adapter.js (49)
[18619:18619:0210/184748.207968:ERROR:CONSOLE(413)] "Uncaught TypeError: this.syncBrowserProxy_.turnOnSync is not a function", source: chrome://settings/people_page/sync_account_control.js (413)
[18619:18619:0210/184749.544505:ERROR:CONSOLE(49)] "Mocha test failed: SyncAccountControl "before each" hook in "SyncAccountControl"
TypeError: Cannot read property 'call' of undefined
", source: file:///b/s/w/ir/chrome/test/data/webui/mocha_adapter.js (49)
[18619:18619:0210/184749.546775:ERROR:CONSOLE(6093)] "Uncaught TypeError: Cannot read property 'isPending' of undefined", source: file:///b/s/w/ir/third_party/mocha/mocha.js (6093)
[18619:18619:0210/184753.193344:WARNING:gaia_auth_fetcher.cc(989)] Could not reach Google Accounts servers: errno -11
[18619:18619:0210/184815.096606:WARNING:gaia_auth_fetcher.cc(989)] Could not reach Google Accounts servers: errno -11
../../base/test/scoped_run_loop_timeout.cc:26: Failure
Failed
RunLoop::Run() timed out.
Google Test trace:
../../chrome/browser/ui/webui/web_ui_test_handler.cc:94: WebUITestHandler::WaitForResult
Stack trace:
#0 0x560f6d110b87 base::test::ScopedRunLoopTimeout::ScopedRunLoopTimeout()::$_0::operator()()
#1 0x560f6d110b1d base::internal::FunctorTraits<>::Invoke<>()
#2 0x560f6d110add base::internal::InvokeHelper<>::MakeItSo<>()
#3 0x560f6d110ab1 _ZN4base8internal7InvokerINS0_9BindStateIZNS_4test20ScopedRunLoopTimeoutC1ENS_9TimeDeltaEE3$_0JEEEFvvEE7RunImplIRKS6_RKNSt4__Cr5tupleIJEEEJEEEvOT_OT0_NSD_16integer_sequenceImJXspT1_EEEE
#4 0x560f6d110a82 base::internal::Invoker<>::Run()
#5 0x7f614f3c0d27 _ZNO4base12OnceCallbackIFvvEE3RunEv
#6 0x7f614f506a5a base::(anonymous namespace)::OnRunLoopTimeout()
#7 0x7f614f50a677 base::internal::FunctorTraits<>::Invoke<>()
#8 0x7f614f50a547 base::internal::InvokeHelper<>::MakeItSo<>()
#9 0x7f614f50a4d3 _ZN4base8internal7InvokerINS0_9BindStateIPFvPNS_7RunLoopENS_12OnceCallbackIFvvEEEEJNS0_17UnretainedWrapperIS3_EENS_17RepeatingCallbackIS6_EEEEES6_E7RunImplIS9_NSt4__Cr5tupleIJSB_SD_EEEJLm0ELm1EEEEvOT_OT0_NSH_16integer_sequenceImJXspT1_EEEE
#10 0x7f614f50a467 base::internal::Invoker<>::RunOnce()
#11 0x7f614f3c0d27 _ZNO4base12OnceCallbackIFvvEE3RunEv
#12 0x7f614f50abc7 base::internal::CancelableCallbackImpl<>::ForwardOnce<>()
#13 0x7f614f50b035 base::internal::FunctorTraits<>::Invoke<>()
#14 0x7f614f50af07 base::internal::InvokeHelper<>::MakeItSo<>()
#15 0x7f614f50ae72 _ZN4base8internal7InvokerINS0_9BindStateIMNS0_22CancelableCallbackImplINS_12OnceCallbackIFvvEEEEEFvvEJNS_7WeakPtrIS7_EEEEES5_E7RunImplIS9_NSt4__Cr5tupleIJSB_EEEJLm0EEEEvOT_OT0_NSF_16integer_sequenceImJXspT1_EEEE
#16 0x7f614f50ae27 base::internal::Invoker<>::RunOnce()
#17 0x7f614f3c0d27 _ZNO4base12OnceCallbackIFvvEE3RunEv
#18 0x7f614f57a35d base::TaskAnnotator::RunTask()
#19 0x7f614f5c164a base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
#20 0x7f614f5c0dab base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork()
#21 0x7f614f5c199c base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork()
#22 0x7f614f46e364 base::MessagePumpGlib::HandleDispatch()
#23 0x7f614f46eea1 base::(anonymous namespace)::WorkSourceDispatch()
#24 0x7f611b332197 g_main_context_dispatch
#25 0x7f611b3323f0 (/lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2+0x4a3ef)
#26 0x7f611b33249c g_main_context_iteration
#27 0x7f614f46e476 base::MessagePumpGlib::Run()
#28 0x7f614f5c257d base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#29 0x7f614f506598 base::RunLoop::Run()
#30 0x560f6e4d628d content::RunThisRunLoop()
#31 0x560f721a865f WebUITestHandler::WaitForResult()
#32 0x560f721a821f WebUITestHandler::RunJavaScriptTestWithResult()
#33 0x560f6d0f109d BaseWebUIBrowserTest::RunJavascriptUsingHandler()
#34 0x560f6d0f1646 BaseWebUIBrowserTest::RunJavascriptAsyncTest()
#35 0x560f6d0f153d BaseWebUIBrowserTest::RunJavascriptTestF()
#36 0x560f6a24dcb6 CrSettingsPeoplePageSyncAccountControlTest_All_Test::RunTestOnMainThread()
#37 0x560f6e41b20d content::BrowserTestBase::ProxyRunTestOnMainThreadLoop()
#38 0x560f6e41f1c3 base::internal::FunctorTraits<>::Invoke<>()
#39 0x560f6e41f131 base::internal::InvokeHelper<>::MakeItSo<>()
#40 0x560f6e41f0d7 _ZN4base8internal7InvokerINS0_9BindStateIMN7content15BrowserTestBaseEFvvEJNS0_17UnretainedWrapperIS4_EEEEEFvvEE7RunImplIS6_NSt4__Cr5tupleIJS8_EEEJLm0EEEEvOT_OT0_NSD_16integer_sequenceImJXspT1_EEEE
#41 0x560f6e41f087 base::internal::Invoker<>::RunOnce()
#42 0x560f67c6a337 _ZNO4base12OnceCallbackIFvvEE3RunEv
#43 0x560f6d247b0b ChromeBrowserMainParts::PreMainMessageLoopRunImpl()
#44 0x560f6d24677d ChromeBrowserMainParts::PreMainMessageLoopRun()
#45 0x7f61436308ce content::BrowserMainLoop::PreMainMessageLoopRun()
#46 0x7f614363c163 base::internal::FunctorTraits<>::Invoke<>()
#47 0x7f614363c071 base::internal::InvokeHelper<>::MakeItSo<>()
#48 0x7f614363bff7 _ZN4base8internal7InvokerINS0_9BindStateIMN7content15BrowserMainLoopEFivEJNS0_17UnretainedWrapperIS4_EEEEEFivEE7RunImplIS6_NSt4__Cr5tupleIJS8_EEEJLm0EEEEiOT_OT0_NSD_16integer_sequenceImJXspT1_EEEE
#49 0x7f614363bfa7 base::internal::Invoker<>::RunOnce()
#50 0x7f61439f3967 _ZNO4base12OnceCallbackIFivEE3RunEv
#51 0x7f614484c7f9 content::StartupTaskRunner::RunAllTasksNow()
#52 0x7f614362f0cb content::BrowserMainLoop::CreateStartupTasks()
#53 0x7f6143640116 content::BrowserMainRunnerImpl::Initialize()
#54 0x7f614362bb64 content::BrowserMain()
#55 0x7f61458a2554 content::RunBrowserProcessMain()
#56 0x7f61458a3bab content::ContentMainRunnerImpl::RunServiceManager()
#57 0x7f61458a34f5 content::ContentMainRunnerImpl::Run()
#58 0x7f614589eda8 content::ContentServiceManagerMainDelegate::RunEmbedderProcess()
#59 0x7f611631c599 service_manager::Main()
#60 0x7f61458a1f70 content::ContentMain()
#61 0x560f6e41acbe content::BrowserTestBase::SetUp()
#62 0x560f6d0deef1 InProcessBrowserTest::SetUp()
#63 0x560f6a4d3074 testing::internal::HandleSehExceptionsInMethodIfSupported<>()
#64 0x560f6a4c47b2 testing::internal::HandleExceptionsInMethodIfSupported<>()

Original change's description:
> cros: Update sync disconnect dialog for SplitSettingsSync
> 
> Browser settings for sync uses a "sign out" dialog to handle when the
> user clicks "Turn off". Depending on the use case the dialog title and
> buttons may say "Turn off" or "Sign out". Update the strings for
> SplitSettingsSync to use "Turn off".
> 
> Because Chrome OS users cannot sign out, wire the dialog's "Turn off"
> button to a new method in PeopleHandler. The existing code path for
> sign out/disconnect assumes DICE, which Chrome OS does not support.
> 
> Bug: 1050677
> Test: manual, button labels are different (and match Linux)
> Change-Id: If8933bb651343d757f04f8b2a5d3d11087610c9d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2047765
> Reviewed-by: Xiyuan Xia <xiyuan@chromium.org>
> Commit-Queue: James Cook <jamescook@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#740068}

TBR=jamescook@chromium.org,xiyuan@chromium.org

Change-Id: I4e6468b9388d7cc887dd358bed9ccd3c0d4714a2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1050677
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2050315
Reviewed-by: Maxim Kolosovskiy <kolos@chromium.org>
Commit-Queue: Maxim Kolosovskiy <kolos@chromium.org>
Cr-Commit-Position: refs/heads/master@{#740297}