[fuchsia] Fix exe_runner.py
This script does not work currently:

Traceback (most recent call last):
  File "build/fuchsia/exe_runner.py", line 36, in <module>
    sys.exit(main())
  File "build/fuchsia/exe_runner.py", line 32, in main
    args.package_dep, args.child_args, run_package_args)
AttributeError: 'Namespace' object has no attribute 'package_dep'

Fix it to account for changes to the package runner.

Change-Id: I292bdd3af4e72add1001d54cbb14e1aa3bdc8ca4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2031993
Commit-Queue: Michael Spang <spang@chromium.org>
Reviewed-by: Kevin Marshall <kmarshall@chromium.org>
Cr-Commit-Position: refs/heads/master@{#737069}