Better registry cleanup in InstallServiceWorkItemTest.
mini_installer_tests ChromeUserLevel and ChromeUserLevelUpdate are
failing with the following error:

AssertionError: In state 'chrome_user_installed_not_inuse', Registry key
HKEY_LOCAL_MACHINE\Software\Chromium exists.

This is most likely due to the change I made in change 2086353 to delete
a value instead of the key.

Now the test will delete the key if the test is the one that created the
key in the first place.

Bug: 1059314
Change-Id: I2b85e1f4c979c52a41aebb41c4951b60cf58a50a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2092939
Commit-Queue: Greg Thompson <grt@chromium.org>
Reviewed-by: Greg Thompson <grt@chromium.org>
Auto-Submit: S. Ganesh <ganesh@chromium.org>
Cr-Commit-Position: refs/heads/master@{#748062}