Add //ui/accessibility:ax_enums_mojo to //content/shell:mojo_bindings' public_deps
Since the public_deps doesn't have //ui/accessiblity:ax_enum_mojo, building //content/shell:mojo_bindings fails occasionally.

E.g.
https://ci.chromium.org/p/chromium/builders/ci/mac-archive-rel/10029
---
[44209/73003] CXX obj/content/shell/mojo_bindings/blink_test.mojom-test-utils.o

FAILED: obj/content/shell/mojo_bindings/blink_test.mojom-test-utils.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
In file included from gen/content/shell/common/blink_test.mojom-test-utils.cc:33:
In file included from ../../content/public/common/common_param_traits_macros.h:29:
In file included from ../../ui/accessibility/ax_param_traits.h:8:
In file included from ../../ui/accessibility/ax_param_traits_macros.h:11:
../../ui/accessibility/ax_event.h:10:10: fatal error: 'ui/accessibility/ax_enums.mojom-forward.h' file not found
---

Change-Id: Ib5791e566332abacd63c8592b064aa1ac26cd878
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2059045
Auto-Submit: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Mike West <mkwst@chromium.org>
Reviewed-by: Mike West <mkwst@chromium.org>
Cr-Commit-Position: refs/heads/master@{#741833}