Revert "Include line numbers in SpeechMonitor async api"
This reverts commit 59211f2c27a7d042b63521d2a1bc3e68b7de2a23.

Reason for revert: Persistent failures on linux-chromeos-chrome waterfall bot

starting https://ci.chromium.org/p/chrome/builders/ci/linux-chromeos-chrome/4305

errors like

../../chrome/browser/chromeos/accessibility/speech_monitor.h:64:54: error: predefined identifier is only valid inside function [-Werror,-Wpredefined-identifier-outside-function]
const base::Location& location = FROM_HERE);

Original change's description:
> Include line numbers in SpeechMonitor async api
> 
> Unfortunately, to resolve base::Location for each api call, we cannot support chaining.
> 
> However, shortening the variable name for
> |speech_monitor_|
> to
> |sm_|
> and not having to indent, we actually save some indent space.
> 
> Also, this change now includes all pending utterances (for understanding the state when the test is waiting).
> 
> Sample output:
> [158567:158567:0325/082550.588956:ERROR:speech_monitor.cc(276)] Still waiting for expectation(s).
> Unsatisfied expectations...
> ExpectSpeech("Fail!Rate 19 percent") RunTestOnMainThread@../../chrome/browser/chromeos/accessibility/spoken_feedback_browsertest.cc:931
> Call() RunTestOnMainThread@../../chrome/browser/chromeos/accessibility/spoken_feedback_browsertest.cc:933
> ExpectSpeech("Pitch 50 percent") RunTestOnMainThread@../../chrome/browser/chromeos/accessibility/spoken_feedback_browsertest.cc:934
> Call() RunTestOnMainThread@../../chrome/browser/chromeos/accessibility/spoken_feedback_browsertest.cc:936
> ExpectSpeech("Reset text to speech settings to default values") RunTestOnMainThread@../../chrome/browser/chromeos/accessibility/spoken_feedback_browsertest.cc:938
> Call() RunTestOnMainThread@../../chrome/browser/chromeos/accessibility/spoken_feedback_browsertest.cc:941
> ExpectSpeech("Rate 19 percent") RunTestOnMainThread@../../chrome/browser/chromeos/accessibility/spoken_feedback_browsertest.cc:942
> Call() RunTestOnMainThread@../../chrome/browser/chromeos/accessibility/spoken_feedback_browsertest.cc:943
> ExpectSpeech("Pitch 50 percent") RunTestOnMainThread@../../chrome/browser/chromeos/accessibility/spoken_feedback_browsertest.cc:944
> 
> pending speech utterances...
> Volume 100 percent
> Rate 19 percent
> 
> Satisfied expectations...
> Call() RunTestOnMainThread@../../chrome/browser/chromeos/accessibility/spoken_feedback_browsertest.cc:926
> ExpectSpeech("Reset text to speech settings to default values") RunTestOnMainThread@../../chrome/browser/chromeos/accessibility/spoken_feedback_browsertest.cc:928
> Call() RunTestOnMainThread@../../chrome/browser/chromeos/accessibility/spoken_feedback_browsertest.cc:930
> 
> Change-Id: If1bdbfb517014e681cb233800eab3f62f608188f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2120741
> Reviewed-by: Akihiro Ota <akihiroota@chromium.org>
> Commit-Queue: David Tseng <dtseng@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#753353}

TBR=dmazzoni@chromium.org,dtseng@chromium.org,akihiroota@chromium.org

Change-Id: Ib3acf61914b3dd81ce2d777961d16de060ae9192
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2121598
Commit-Queue: Trent Apted <tapted@chromium.org>
Reviewed-by: Trent Apted <tapted@chromium.org>
Cr-Commit-Position: refs/heads/master@{#753518}