Revert "Remove support for Tab Freezing"
This reverts commit d0332c346b8aefd7ebd79e9faa8ed582f86695c0.

Reason for revert: Introduced failure on browser_tests DiscardsTest.All

First failure here:
https://ci.chromium.org/p/chromium/builders/ci/linux-chromeos-dbg/19162
[9313:9313:0615/094609.344774:INFO:CONSOLE(1065)] "Running TestCase DiscardsTest.All", source: file:///b/s/w/ir/chrome/test/data/webui/test_api.js (1065)
[9313:9313:0615/094609.353925:WARNING:CONSOLE(34)] "Error: Assertion failed: Unsupported sort key: canFreeze
    at assert (chrome://resources/js/assert.m.js:26:19)
    at assertNotReached (chrome://resources/js/assert.m.js:64:3)
    at compareTabDiscardsInfos (chrome://discards/discards_tab.js:73:3)
    at chrome://test/discards/discards_test.js:42:22
    at Array.forEach (<anonymous>)
    at Context.<anonymous> (chrome://test/discards/discards_test.js:41:10)
    at callFn (file:///b/s/w/ir/third_party/mocha/mocha.js:5342:21)
    at Test.Runnable.run (file:///b/s/w/ir/third_party/mocha/mocha.js:5334:7)
    at Runner.runTest (file:///b/s/w/ir/third_party/mocha/mocha.js:5990:10)
    at file:///b/s/w/ir/third_party/mocha/mocha.js:6108:12", source: chrome://resources/js/assert.m.js (34)
[9313:9313:0615/094609.364579:ERROR:CONSOLE(49)] "Mocha test failed: discards CompareTabDiscardsInfo
Error: Assertion failed: Unsupported sort key: canFreeze
    at assert (chrome://resources/js/assert.m.js:26:19)
    at assertNotReached (chrome://resources/js/assert.m.js:64:3)
    at compareTabDiscardsInfos (chrome://discards/discards_tab.js:73:3)
    at chrome://test/discards/discards_test.js:42:22
    at Array.forEach (<anonymous>)
    at Context.<anonymous> (chrome://test/discards/discards_test.js:41:10)
", source: file:///b/s/w/ir/chrome/test/data/webui/mocha_adapter.js (49)

Original change's description:
> Remove support for Tab Freezing
> 
> This feature has been abandoned.
> 
> Bug: 844426
> Change-Id: I777dcb72edd7941778374cc2fbff1e2c966bdac1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2239374
> Reviewed-by: Will Harris <wfh@chromium.org>
> Reviewed-by: Ken Buchanan <kenrb@chromium.org>
> Reviewed-by: Alexei Svitkine <asvitkine@chromium.org>
> Reviewed-by: Avi Drissman <avi@chromium.org>
> Reviewed-by: François Doray <fdoray@chromium.org>
> Commit-Queue: Alexei Svitkine <asvitkine@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#778280}

TBR=avi@chromium.org,kenrb@chromium.org,fdoray@chromium.org,asvitkine@chromium.org,wfh@chromium.org,sebmarchand@chromium.org

Change-Id: I3dafddea7f11bffea171cd8a80ea51368943dd83
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 844426
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2246920
Reviewed-by: Robert Flack <flackr@chromium.org>
Commit-Queue: Robert Flack <flackr@chromium.org>
Cr-Commit-Position: refs/heads/master@{#778411}