Fix compilation with Ozone build for chromium browser.
Compiling Error:

../../chrome/browser/shell_integration_linux.cc:294:13: error: unused function 'QuoteCommandLineForDesktopFileExec' [-Werror,-Wunused-function]
std::string QuoteCommandLineForDesktopFileExec(
            ^
../../chrome/browser/shell_integration_linux.cc:310:12: error: unused variable 'kDesktopEntry' [-Werror,-Wunused-const-variable]
const char kDesktopEntry[] = "Desktop Entry";
           ^
../../chrome/browser/shell_integration_linux.cc:312:12: error: unused variable 'kXdgOpenShebang' [-Werror,-Wunused-const-variable]
const char kXdgOpenShebang[] = "#!/usr/bin/env xdg-open";
           ^
3 errors generated.

The above mentioned function and variables are only used from GetNoDisplayFromDesktopFile,
only when support for GLIB is enabled.

Review URL: https://codereview.chromium.org/499823002