Revert "Update emulated position on each XRFrame"
This reverts commit 8be89ae08126913ff4447927ac5a087b8d6babcf.

Reason for revert: Build failure:

https://ci.chromium.org/p/chromium/builders/ci/Win%20x64%20Builder/79827
[4142/15096] CXX obj/device/vr/vr/openxr_controller.obj
FAILED: obj/device/vr/vr/openxr_controller.obj
C:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
../../device/vr/openxr/openxr_controller.cc(204,19): error: no member named 'emulated_position' in 'device::mojom::XRInputSourceDescription'
description_->emulated_position = false;
~~~~~~~~~~~~  ^
1 error generated.

Original change's description:
> Update emulated position on each XRFrame
> 
> For both the head poses and input poses, send this value through mojo
> from the device process to the renderer process on every frame.
> 
> Bug: 969131
> Change-Id: Ie895deb75bddb6dd883d09828cfcb30f335d3793
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1825478
> Auto-Submit: Jacob DeWitt <jacde@chromium.org>
> Commit-Queue: Will Harris <wfh@chromium.org>
> Reviewed-by: Will Harris <wfh@chromium.org>
> Reviewed-by: Klaus Weidner <klausw@chromium.org>
> Reviewed-by: Alexander Cooper <alcooper@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#701389}

TBR=dcheng@chromium.org,wfh@chromium.org,klausw@chromium.org,jacde@chromium.org,alcooper@chromium.org

Change-Id: I91ec66842b8f0a14bcb85145843fb4d617847066
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 969131
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1833005
Reviewed-by: Tsuyoshi Horo <horo@chromium.org>
Commit-Queue: Tsuyoshi Horo <horo@chromium.org>
Cr-Commit-Position: refs/heads/master@{#701401}