tcmalloc: Include <atomic> for std::atomic and std::memory_order_acquire
IWYU. This fixes the libstdc++ build after commit 64d752de1 ("Use new
tcmalloc on Linux builds by default"):

    In file included from ../../base/allocator/allocator_extension.cc:12:
    ../../third_party/tcmalloc/chromium/src/gperftools/malloc_extension.h:442:15:
    error: no template named 'atomic' in namespace 'std'
      static std::atomic<MallocExtension*> current_instance_;
             ~~~~~^
    ../../third_party/tcmalloc/chromium/src/gperftools/malloc_extension.h:352:40:
    error: no member named 'memory_order_acquire' in namespace 'std'
        return current_instance_.load(std::memory_order_acquire);
                                      ~~~~~^

Bug: 724399, 957519
Change-Id: I76578a11e2c452b1a945edd0243f2dba34d3cfb5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1591512
Commit-Queue: Will Harris <wfh@chromium.org>
Reviewed-by: Will Harris <wfh@chromium.org>
Reviewed-by: Gabriel Marin <gmx@chromium.org>
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#656878}