Detect out-of-order Assistant responses
This will help us detect failures caused by LibAssistant sending the
|OnInteractionFinished| event before all the responses (like
|OnOpenAndroidApp|) are received.

This will help us detect if the current test failures are caused by
this, or if there is some other cause we need to find.

The failure looks as follows (newlines added for commit message only):

assistant.OpenAndroidApp  [ FAIL ]
  Failed to send the Assistant text query:
  Error: OnOpenAppResponse was called after the interaction was closed


Bug: b/157144814
Change-Id: I22b29f1d7bcdebd3844cf996ffe1fbfece42754d
Tests: Tast tests with pattern "*ssistant*"
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2211049
Commit-Queue: Jeroen Dhollander <jeroendh@google.com>
Reviewed-by: Tao Wu <wutao@chromium.org>
Reviewed-by: Xiaohui Chen <xiaohuic@chromium.org>
Reviewed-by: Achuith Bhandarkar <achuith@chromium.org>
Cr-Commit-Position: refs/heads/master@{#771150}