gpu: Convert a use of has_key()
has_key() has been removed in Python 3.
Use the 'in' operator which works in both Python 2 and 3.

Traceback (most recent call last):
  File "../../gpu/config/process_json.py", line 961, in <module>
    sys.exit(main(sys.argv[1:]))
  File "../../gpu/config/process_json.py", line 935, in main
    process_software_rendering_list(
  File "../../gpu/config/process_json.py", line 810, in process_software_rendering_list
    process_json_file(
  File "../../gpu/config/process_json.py", line 771, in process_json_file
    write_entry(entry, total_features, feature_tag, unique_symbol_id,
  File "../../gpu/config/process_json.py", line 677, in write_entry
    write_conditions(entry_id, False, -1, entry, unique_symbol_id,
  File "../../gpu/config/process_json.py", line 525, in write_conditions
    if driver_version.has_key('value2'):
AttributeError: 'dict' object has no attribute 'has_key'

Bug: 941669
Change-Id: Ib0f629fdcd7d1a72c4b1dd5f846a33007154e46d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2130267
Reviewed-by: Kenneth Russell <kbr@chromium.org>
Commit-Queue: Kenneth Russell <kbr@chromium.org>
Commit-Queue: Raul Tambre <raul@tambre.ee>
Auto-Submit: Raul Tambre <raul@tambre.ee>
Cr-Commit-Position: refs/heads/master@{#755043}