Revert "Reland "[fuchsia] Register Views with Fuchsia Accessibility APIs""
This reverts commit fe8612d0797e97ab199380ec31df3afdfa226ed5.

Reason for revert: caused compile failure on Fuchsia ARM64 bot

Sample build: https://ci.chromium.org/p/chromium/builders/ci/Fuchsia%20ARM64/84538

Sample log: https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket.appspot.com/8902744172135456592/+/steps/compile/0/stdout?format=raw

---
[1007/1649] CXX obj/fuchsia/engine/web_engine_unittests__exec/accessibility_bridge_unittest.o
FAILED: ../../fuchsia/engine/browser/accessibility_bridge_unittest.cc:69:25: error: no member named 'ScopedTaskEnvironment' in namespace 'base::test'; did you mean 'TaskEnvironment'?
base::test::ScopedTaskEnvironment::MainThreadType::IO),
~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
TaskEnvironment
../../base/test/task_environment.h:83:7: note: 'TaskEnvironment' declared here
class TaskEnvironment {
^
1 error generated.
---

Original change's description:
> Reland "[fuchsia] Register Views with Fuchsia Accessibility APIs"
> 
> This is a reland of b02a397f538eb408e18f2486686e23a294467bc1
> 
> This includes the missing deps that caused the component builds to fail
> and EXPORTs the AccessibilityBridge class for testing.
> 
> Original change's description:
> > [fuchsia] Register Views with Fuchsia Accessibility APIs
> >
> > * Add the AccessibilityBridge class skeleton, which will eventually
> > handle the logic for conversion between Chromium and Fuchsia
> > accessibility data structures.
> > * Register a ViewRef to the Fuchsia SemanticsManager.
> >
> > Test: Added AccessibilityBridgeUnitTest.*
> >
> > Bug: 973095
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1708043
> > Commit-Queue: Sharon Yang <yangsharon@chromium.org>
> > Reviewed-by: Sergey Ulanov <sergeyu@chromium.org>
> > Reviewed-by: Wez <wez@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#693914}
> 
> Bug: 973095
> Change-Id: I3a5a958fc88a5804023372453420863e97f9df74
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1792460
> Reviewed-by: Wez <wez@chromium.org>
> Commit-Queue: Sharon Yang <yangsharon@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#695013}

TBR=wez@chromium.org,sergeyu@chromium.org,yangsharon@chromium.org

Change-Id: I4f21d8978e9761506bc31d24d9b2f64ee87f8287
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 973095
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1792508
Reviewed-by: Takashi Sakamoto <tasak@google.com>
Commit-Queue: Takashi Sakamoto <tasak@google.com>
Cr-Commit-Position: refs/heads/master@{#695016}