Revert "WebUI Tab Strip: Animate tabs when moved"
This reverts commit dc9187da36c6f8dfda281f5722a1769398b1f8d3.

Reason for revert: Causing failures on Network Service Linux:

https://ci.chromium.org/p/chromium/builders/ci/Network%20Service%20Linux/6688

Mocha test failed: TabList PlaceTabElementAnimatesTabMoved
AssertionError: expected 2 to equal 1

Original change's description:
> WebUI Tab Strip: Animate tabs when moved
> 
> This CL adds animation when an ungrouped, unpinned tab is moved, to
> mostly facilitate the drag and drop experience. When the TabList's
> placeTabElement is called, the method first determines if the
> placement is causing a TabElement to move, then identifies which
> elements the TabElement is being dragged across, and finally
> animates the necessary distances for each TabElement.
> 
> Bug: 1082344
> Change-Id: Ia0b55f4c8539429969197258d148ce236b29e7e2
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2215248
> Commit-Queue: John Lee <johntlee@chromium.org>
> Reviewed-by: dpapad <dpapad@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#774469}

TBR=dpapad@chromium.org,johntlee@chromium.org

Change-Id: Id1e22487b0aa2e48ba31edabf0ffe4554b2c0a63
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1082344
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2228370
Reviewed-by: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Commit-Queue: Giovanni Ortuño Urquidi <ortuno@chromium.org>
Cr-Commit-Position: refs/heads/master@{#774498}