Revert of cc: Add occlusion checker as a fixed view of occlusion tracker. (patchset #7 id:120001 of https://codereview.chromium.org/547723002/)
Reason for revert:
Broke linux GN build: http://build.chromium.org/p/chromium.linux/builders/Linux%20GN/builds/11591

[496/2225 | 35.477] CXX obj/ui/views/controls/views.focusable_border.o
[497/2225 | 35.633] CXX obj/ui/views/controls/views.glow_hover_controller.o
FAILED: /mnt/data/b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/cc/layers/cc_unittests.picture_layer_impl_unittest.o.d -DCHROMIUM_BUILD -DENABLE_NOTIFICATIONS -DENABLE_EGLIMAGE=1 -DENABLE_BACKGROUND=1 -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DENABLE_MDNS=1 -DENABLE_PEPPER_CDMS -DENABLE_PLUGINS=1 -DENABLE_PRINTING=1 -DENABLE_FULL_PRINTING=1 -DENABLE_SPELLCHECK=1 -DUSE_UDEV -DTOOLKIT_VIEWS=1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_ASH=1 -DUSE_AURA=1 -DUSE_CAIRO=1 -DUSE_CLIPBOARD_AURAX11=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_GLIB=1 -DUSE_NSS=1 -DUSE_X11=1 -DUSE_XI2_MT=2 -DDISABLE_NACL -DENABLE_EXTENSIONS=1 -DENABLE_CONFIGURATION_POLICY -DENABLE_TASK_MANAGER=1 -DENABLE_THEMES=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_MANAGED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_REMOTING=1 -DENABLE_GOOGLE_NOW=1 -DENABLE_ONE_CLICK_SIGNIN -DCR_CLANG_REVISION=214024 -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DGL_GLEXT_PROTOTYPES -DMEDIA_DISABLE_LIBVPX -DSK_SUPPORT_LEGACY_PUBLIC_IMAGEINFO_FIELDS -DSK_IGNORE_PROPER_FRACTIONAL_SCALING -DSK_SUPPORT_LEGACY_PICTURE_CLONE -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DSK_SUPPORT_LEGACY_IMAGECACHE_NAME -DSK_LEGACY_PICTURE_SIZE_API -DSK_LEGACY_PICTURE_DRAW_API -DSK_ENABLE_INST_COUNT=0 -DGR_GL_CUSTOM_SETUP_HEADER=\"GrGLConfig_chrome.h\" -DSK_ENABLE_LEGACY_API_ALIASING=1 -DSK_ATTR_DEPRECATED=SK_NOTHING_ARG1 -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_WILL_NEVER_DRAW_PERSPECTIVE_TEXT -DSK_SUPPORT_LEGACY_GETTOTALCLIP -DSK_SUPPORT_GPU=1 -DSK_USE_POSIX_THREADS -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=0 -DGTEST_HAS_RTTI=0 -DUNIT_TEST -I../.. -Igen -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../third_party/khronos -I../../gpu -Igen/ui/gl -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/src/core -I../../third_party/skia/src/image -I../../third_party/skia/src/opts -I../../third_party/skia/src/ports -I../../third_party/skia/src/sfnt -I../../third_party/skia/src/utils -I../../third_party/skia/src/lazy -I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu -I../../testing/gtest/include -I../../testing/gmock/include -fno-strict-aliasing -fstack-protector --param=ssp-buffer-size=4 -m64 -funwind-tables -fPIC -pipe -pthread -fcolor-diagnostics -Wall -Wextra -Wsign-compare -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-char-subscripts -Wno-covered-switch-default -Wno-deprecated-register -Wno-unused-function -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Wheader-hygiene -Wstring-conversion -fno-ident -fdata-sections -ffunction-sections -O2 -g2 -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -Wno-reserved-user-defined-literal -fno-rtti -fno-exceptions -c ../../cc/layers/picture_layer_impl_unittest.cc -o obj/cc/layers/cc_unittests.picture_layer_impl_unittest.o
../../cc/layers/picture_layer_impl_unittest.cc:2578:31:error: reference to type 'const cc::Occlusion' could not bind to an rvalue of type 'long'
  pending_layer_->UpdateTiles(NULL);
                              ^~~~
/mnt/data/b/build/slave/Linux_GN/build/src/third_party/llvm-build/Release+Asserts/bin/../lib/clang/3.5.0/include/stddef.h:96:18: note: expanded from macro 'NULL'
#    define NULL __null
                 ^~~~~~
../../cc/layers/picture_layer_impl.h:113:24: note: passing argument to parameter 'occlusion_in_content_space' here
      const Occlusion& occlusion_in_content_space) OVERRIDE;
                       ^
../../cc/layers/picture_layer_impl_unittest.cc:2608:31:error: reference to type 'const cc::Occlusion' could not bind to an rvalue of type 'long'
  pending_layer_->UpdateTiles(NULL);
                              ^~~~
/mnt/data/b/build/slave/Linux_GN/build/src/third_party/llvm-build/Release+Asserts/bin/../lib/clang/3.5.0/include/stddef.h:96:18: note: expanded from macro 'NULL'
#    define NULL __null
                 ^~~~~~
../../cc/layers/picture_layer_impl.h:113:24: note: passing argument to parameter 'occlusion_in_content_space' here
      const Occlusion& occlusion_in_content_space) OVERRIDE;
                       ^
2 errors generated.
ninja: build stopped: subcommand failed.

Original issue's description:
> cc: Add occlusion checker as a fixed view of occlusion tracker.
>
> This patch adds an occlusion checker to get the state of
> occlusion tracker for permanent checks. That is, occlusion
> checker does not have to be queried during a layer walk.
>
> BUG=410932
> R=danakj
>
> Committed: https://crrev.com/1af780529157c94a9e0f05bcf478543b85714f6b
> Cr-Commit-Position: refs/heads/master@{#294205}

TBR=danakj@chromium.org,vmpstr@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=410932

Review URL: https://codereview.chromium.org/551463005